
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label lblVersion;

	private global::Gtk.Fixed fixed3;

	private global::Gtk.Button btnSave;

	private global::Gtk.Button btnSaveAs;

	private global::Gtk.Button btnPrefs;

	private global::Gtk.Button btnAbout;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label5;

	private global::Gtk.Button btnOpenScript;

	private global::Gtk.Button btnNewScriptTR4;

	private global::Gtk.Button btnNewScriptTPC;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label6;

	private global::Gtk.Button btnOpenLvl;

	private global::Gtk.Button btnNewLevel;

	private global::Gtk.Label label1;

	private global::Gtk.Notebook notebook2;

	private global::TRLevelUtility.ListAddRem larLevels;

	private global::Gtk.Label label8;

	private global::Gtk.HBox hbox5;

	private global::TRLevelUtility.ListAddRem larTPCrpl;

	private global::TRLevelUtility.ListAddRem larTPCcut;

	private global::TRLevelUtility.ListAddRem larTPClegal;

	private global::Gtk.Label label9;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox30;

	private global::Gtk.Frame frame5;

	private global::Gtk.Alignment GtkAlignment35;

	private global::Gtk.VBox vbox20;

	private global::Gtk.HBox hbox35;

	private global::Gtk.CheckButton cbxTPCPSX;

	private global::Gtk.CheckButton cbxTPCtr2beta;

	private global::Gtk.CheckButton cbxTPCTR3;

	private global::Gtk.Table table2;

	private global::Gtk.ComboBox cbxTPCLanguage;

	private global::Gtk.Label label25;

	private global::Gtk.Label label26;

	private global::Gtk.Label lblTPCDesc;

	private global::TRLevelUtility.TwoBaseEntry tbeTPCCypher;

	private global::Gtk.VBox vbox16;

	private global::Gtk.HBox hbox28;

	private global::Gtk.Label label24;

	private global::Gtk.ComboBox cbxTPCLoadDesc;

	private global::Gtk.ScrolledWindow GtkScrolledWindow12;

	private global::Gtk.TextView tvTPCDesc;

	private global::Gtk.Label GtkLabel54;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment36;

	private global::TRLevelUtility.ListAddRem larTPCdemolvls;

	private global::Gtk.Label GtkLabel55;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment19;

	private global::Gtk.Table table1;

	private global::Gtk.Label label13;

	private global::Gtk.Label label14;

	private global::Gtk.Label label15;

	private global::Gtk.Label label16;

	private global::Gtk.Label label17;

	private global::Gtk.Label label18;

	private global::Gtk.Label label19;

	private global::Gtk.Label label20;

	private global::Gtk.Label label21;

	private global::TRLevelUtility.ScriptActionWgt tpcFirstOption;

	private global::Gtk.SpinButton tpcNoInputTime;

	private global::TRLevelUtility.ScriptActionWgt tpcOnDeathDemoMode;

	private global::TRLevelUtility.ScriptActionWgt tpcOnDeathInGame;

	private global::TRLevelUtility.ScriptActionWgt tpcOnDemoEnd;

	private global::TRLevelUtility.ScriptActionWgt tpcOnDemoInterrupt;

	private global::Gtk.SpinButton tpcSecretSound;

	private global::TRLevelUtility.ScriptActionWgt tpcTitleReplace;

	private global::Gtk.SpinButton tpcTitleSound;

	private global::Gtk.Label GtkLabel22;

	private global::Gtk.Frame frame4;

	private global::Gtk.Alignment GtkAlignment20;

	private global::Gtk.HBox hbox18;

	private global::Gtk.VBox vboxTPCFlags;

	private global::TRLevelUtility.TwoBaseEntry tbeTPCFlags;

	private global::Gtk.CheckButton cbxTPCFlag1;

	private global::Gtk.CheckButton cbxTPCFlag2;

	private global::Gtk.CheckButton cbxTPCFlag3;

	private global::Gtk.CheckButton cbxTPCFlag4;

	private global::Gtk.CheckButton cbxTPCFlag5;

	private global::Gtk.CheckButton cbxTPCFlag6;

	private global::Gtk.CheckButton cbxTPCFlag7;

	private global::Gtk.CheckButton cbxTPCFlag8;

	private global::Gtk.CheckButton cbxTPCFlag9;

	private global::Gtk.CheckButton cbxTPCFlag10;

	private global::Gtk.CheckButton cbxTPCFlag11;

	private global::Gtk.CheckButton cbxTPCFlag12;

	private global::Gtk.Label GtkLabel35;

	private global::Gtk.Label label10;

	private global::Gtk.HBox hbox32;

	private global::Gtk.Frame frame7;

	private global::Gtk.Alignment GtkAlignment43;

	private global::TRLevelUtility.ListAddRem larTPCscSlots;

	private global::Gtk.Label GtkLabel62;

	private global::Gtk.VBox vbox21;

	private global::Gtk.Frame frame8;

	private global::Gtk.Alignment GtkAlignment44;

	private global::TRLevelUtility.ListAddRem larTPCscCommands;

	private global::Gtk.Label GtkLabel63;

	private global::Gtk.Frame frame9;

	private global::Gtk.Alignment GtkAlignment45;

	private global::Gtk.Table table4;

	private global::Gtk.ComboBox cbxTPCCommand;

	private global::Gtk.Label label23;

	private global::Gtk.Label lblTPCcmdHelp;

	private global::Gtk.Label lblTPCoperandName;

	private global::Gtk.SpinButton sbTPCOperand;

	private global::Gtk.Label GtkLabel64;

	private global::Gtk.Label label11;

	private global::Gtk.Notebook notebook3;

	private global::TRLevelUtility.ListAddRem larTPCgs;

	private global::Gtk.Label label27;

	private global::TRLevelUtility.ListAddRem larTPCps;

	private global::Gtk.Label label29;

	private global::TRLevelUtility.ListAddRem larTPCpss;

	private global::Gtk.Label label2;

	private global::TRLevelUtility.ListAddRem larTPCPuzzle;

	private global::Gtk.Label label31;

	private global::TRLevelUtility.ListAddRem larTPCPickups;

	private global::Gtk.Label label36;

	private global::TRLevelUtility.ListAddRem larTPCKeys;

	private global::Gtk.Label label37;

	private global::TRLevelUtility.ListAddRem larTPCSecrets;

	private global::Gtk.Label label28;

	private global::TRLevelUtility.ListAddRem larTPCSpecial;

	private global::Gtk.Label label38;

	private global::Gtk.Label label32;

	private global::Gtk.Label label33;

	private global::Gtk.VBox vbox27;

	private global::Gtk.HBox hbox46;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment56;

	private global::Gtk.HBox hbox43;

	private global::Gtk.Table table3;

	private global::Gtk.Label label12;

	private global::Gtk.Label label7;

	private global::Gtk.SpinButton sbTR4InputTimeout;

	private global::TRLevelUtility.TwoBaseEntry tbeTR4Security;

	private global::Gtk.Label GtkLabel72;

	private global::Gtk.Frame frame6;

	private global::Gtk.Alignment GtkAlignment57;

	private global::Gtk.VBox vboxTR4Flags;

	private global::TRLevelUtility.TwoBaseEntry tbeTR4Flags;

	private global::Gtk.HBox hboxTR4Flags;

	private global::Gtk.CheckButton cbxTR4Flag1;

	private global::Gtk.CheckButton cbxTR4Flag2;

	private global::Gtk.CheckButton cbxTR4Flag3;

	private global::Gtk.CheckButton cbxTR4Flag4;

	private global::Gtk.CheckButton cbxTR4Flag8;

	private global::Gtk.Label GtkLabel75;

	private global::Gtk.Notebook notebook4;

	private global::Gtk.HBox hbox47;

	private global::Gtk.ScrolledWindow GtkScrolledWindow23;

	private global::Gtk.NodeView nodeview1;

	private global::Gtk.Label label30;

	private global::Gtk.Label label22;

	private global::Gtk.Label label34;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label35;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("TRLevelUtility");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(10));
		this.DefaultWidth = 1060;
		this.DefaultHeight = 760;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.hbox1.BorderWidth = ((uint)(3));
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblVersion = new global::Gtk.Label();
		this.lblVersion.Name = "lblVersion";
		this.lblVersion.LabelProp = global::Mono.Unix.Catalog.GetString("TRLevelUtility version ");
		this.hbox1.Add(this.lblVersion);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblVersion]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox1.Add(this.fixed3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed3]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSave = new global::Gtk.Button();
		this.btnSave.CanFocus = true;
		this.btnSave.Name = "btnSave";
		this.btnSave.UseUnderline = true;
		this.btnSave.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnSave.Label = global::Mono.Unix.Catalog.GetString("_Save");
		global::Gtk.Image w3 = new global::Gtk.Image();
		w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.LargeToolbar);
		this.btnSave.Image = w3;
		this.hbox1.Add(this.btnSave);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSave]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSaveAs = new global::Gtk.Button();
		this.btnSaveAs.CanFocus = true;
		this.btnSaveAs.Name = "btnSaveAs";
		this.btnSaveAs.UseUnderline = true;
		this.btnSaveAs.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnSaveAs.Label = global::Mono.Unix.Catalog.GetString("Save _As");
		global::Gtk.Image w5 = new global::Gtk.Image();
		w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save-as", global::Gtk.IconSize.LargeToolbar);
		this.btnSaveAs.Image = w5;
		this.hbox1.Add(this.btnSaveAs);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSaveAs]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnPrefs = new global::Gtk.Button();
		this.btnPrefs.CanFocus = true;
		this.btnPrefs.Name = "btnPrefs";
		this.btnPrefs.UseUnderline = true;
		this.btnPrefs.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnPrefs.Label = global::Mono.Unix.Catalog.GetString("_Preferences");
		global::Gtk.Image w7 = new global::Gtk.Image();
		w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-preferences", global::Gtk.IconSize.LargeToolbar);
		this.btnPrefs.Image = w7;
		this.hbox1.Add(this.btnPrefs);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnPrefs]));
		w8.Position = 4;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnAbout = new global::Gtk.Button();
		this.btnAbout.CanFocus = true;
		this.btnAbout.Name = "btnAbout";
		this.btnAbout.UseUnderline = true;
		this.btnAbout.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnAbout.Label = global::Mono.Unix.Catalog.GetString("_About");
		global::Gtk.Image w9 = new global::Gtk.Image();
		w9.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-about", global::Gtk.IconSize.LargeToolbar);
		this.btnAbout.Image = w9;
		this.hbox1.Add(this.btnAbout);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnAbout]));
		w10.Position = 5;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		this.notebook1.ShowBorder = false;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 32;
		this.vbox2.BorderWidth = ((uint)(12));
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Script file\nSupported formats: TR2-3 (TOMBPC.DAT), TR4-5 (SCRIPT.DAT)\nAlso suppor" +
				"ts uncompiled TXT script");
		this.hbox2.Add(this.label5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label5]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnOpenScript = new global::Gtk.Button();
		this.btnOpenScript.CanFocus = true;
		this.btnOpenScript.Name = "btnOpenScript";
		this.btnOpenScript.UseUnderline = true;
		this.btnOpenScript.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnOpenScript.Label = global::Mono.Unix.Catalog.GetString("_Open");
		global::Gtk.Image w13 = new global::Gtk.Image();
		w13.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.LargeToolbar);
		this.btnOpenScript.Image = w13;
		this.hbox2.Add(this.btnOpenScript);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnOpenScript]));
		w14.PackType = ((global::Gtk.PackType)(1));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnNewScriptTR4 = new global::Gtk.Button();
		this.btnNewScriptTR4.CanFocus = true;
		this.btnNewScriptTR4.Name = "btnNewScriptTR4";
		this.btnNewScriptTR4.UseUnderline = true;
		this.btnNewScriptTR4.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnNewScriptTR4.Label = global::Mono.Unix.Catalog.GetString("_New TR4-5 script");
		global::Gtk.Image w15 = new global::Gtk.Image();
		w15.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-new", global::Gtk.IconSize.LargeToolbar);
		this.btnNewScriptTR4.Image = w15;
		this.hbox2.Add(this.btnNewScriptTR4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnNewScriptTR4]));
		w16.PackType = ((global::Gtk.PackType)(1));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnNewScriptTPC = new global::Gtk.Button();
		this.btnNewScriptTPC.CanFocus = true;
		this.btnNewScriptTPC.Name = "btnNewScriptTPC";
		this.btnNewScriptTPC.UseUnderline = true;
		this.btnNewScriptTPC.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnNewScriptTPC.Label = global::Mono.Unix.Catalog.GetString("New _TR2-3 script");
		global::Gtk.Image w17 = new global::Gtk.Image();
		w17.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-new", global::Gtk.IconSize.LargeToolbar);
		this.btnNewScriptTPC.Image = w17;
		this.hbox2.Add(this.btnNewScriptTPC);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnNewScriptTPC]));
		w18.PackType = ((global::Gtk.PackType)(1));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Level file\nSupported formats: TR1 (.PHD, .TUB), TR2-3 (.TR2), TR4 (.TR4), TR5 (.T" +
				"RC)\nSupports converting levels between versions and platforms (PC/PSX)");
		this.hbox3.Add(this.label6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label6]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnOpenLvl = new global::Gtk.Button();
		this.btnOpenLvl.CanFocus = true;
		this.btnOpenLvl.Name = "btnOpenLvl";
		this.btnOpenLvl.UseUnderline = true;
		this.btnOpenLvl.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnOpenLvl.Label = global::Mono.Unix.Catalog.GetString("_Open");
		global::Gtk.Image w21 = new global::Gtk.Image();
		w21.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.LargeToolbar);
		this.btnOpenLvl.Image = w21;
		this.hbox3.Add(this.btnOpenLvl);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnOpenLvl]));
		w22.PackType = ((global::Gtk.PackType)(1));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnNewLevel = new global::Gtk.Button();
		this.btnNewLevel.CanFocus = true;
		this.btnNewLevel.Name = "btnNewLevel";
		this.btnNewLevel.UseUnderline = true;
		this.btnNewLevel.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnNewLevel.Label = global::Mono.Unix.Catalog.GetString("_New");
		global::Gtk.Image w23 = new global::Gtk.Image();
		w23.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-new", global::Gtk.IconSize.LargeToolbar);
		this.btnNewLevel.Image = w23;
		this.hbox3.Add(this.btnNewLevel);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnNewLevel]));
		w24.PackType = ((global::Gtk.PackType)(1));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.notebook1.Add(this.vbox2);
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Home");
		this.notebook1.SetTabLabel(this.vbox2, this.label1);
		this.label1.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.notebook2 = new global::Gtk.Notebook();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 3;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.larLevels = new global::TRLevelUtility.ListAddRem();
		this.larLevels.Events = ((global::Gdk.EventMask)(256));
		this.larLevels.Name = "larLevels";
		this.larLevels.HideAddRem = false;
		this.notebook2.Add(this.larLevels);
		// Notebook tab
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Levels");
		this.notebook2.SetTabLabel(this.larLevels, this.label8);
		this.label8.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Homogeneous = true;
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.larTPCrpl = new global::TRLevelUtility.ListAddRem();
		this.larTPCrpl.Events = ((global::Gdk.EventMask)(256));
		this.larTPCrpl.Name = "larTPCrpl";
		this.larTPCrpl.HideAddRem = false;
		this.hbox5.Add(this.larTPCrpl);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.larTPCrpl]));
		w28.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.larTPCcut = new global::TRLevelUtility.ListAddRem();
		this.larTPCcut.Events = ((global::Gdk.EventMask)(256));
		this.larTPCcut.Name = "larTPCcut";
		this.larTPCcut.HideAddRem = false;
		this.hbox5.Add(this.larTPCcut);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.larTPCcut]));
		w29.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.larTPClegal = new global::TRLevelUtility.ListAddRem();
		this.larTPClegal.Events = ((global::Gdk.EventMask)(256));
		this.larTPClegal.Name = "larTPClegal";
		this.larTPClegal.HideAddRem = false;
		this.hbox5.Add(this.larTPClegal);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.larTPClegal]));
		w30.Position = 2;
		this.notebook2.Add(this.hbox5);
		global::Gtk.Notebook.NotebookChild w31 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.hbox5]));
		w31.Position = 1;
		// Notebook tab
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("FMV / Cutscenes");
		this.notebook2.SetTabLabel(this.hbox5, this.label9);
		this.label9.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox30 = new global::Gtk.HBox();
		this.hbox30.Name = "hbox30";
		this.hbox30.Spacing = 6;
		// Container child hbox30.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment35 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment35.Name = "GtkAlignment35";
		this.GtkAlignment35.LeftPadding = ((uint)(12));
		// Container child GtkAlignment35.Gtk.Container+ContainerChild
		this.vbox20 = new global::Gtk.VBox();
		this.vbox20.Name = "vbox20";
		this.vbox20.Spacing = 6;
		// Container child vbox20.Gtk.Box+BoxChild
		this.hbox35 = new global::Gtk.HBox();
		this.hbox35.Name = "hbox35";
		this.hbox35.Spacing = 6;
		// Container child hbox35.Gtk.Box+BoxChild
		this.cbxTPCPSX = new global::Gtk.CheckButton();
		this.cbxTPCPSX.CanFocus = true;
		this.cbxTPCPSX.Name = "cbxTPCPSX";
		this.cbxTPCPSX.Label = global::Mono.Unix.Catalog.GetString("Is PSX");
		this.cbxTPCPSX.DrawIndicator = true;
		this.cbxTPCPSX.UseUnderline = true;
		this.cbxTPCPSX.FocusOnClick = false;
		this.hbox35.Add(this.cbxTPCPSX);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.cbxTPCPSX]));
		w32.Position = 0;
		// Container child hbox35.Gtk.Box+BoxChild
		this.cbxTPCtr2beta = new global::Gtk.CheckButton();
		this.cbxTPCtr2beta.CanFocus = true;
		this.cbxTPCtr2beta.Name = "cbxTPCtr2beta";
		this.cbxTPCtr2beta.Label = global::Mono.Unix.Catalog.GetString("Is TR2 Beta");
		this.cbxTPCtr2beta.DrawIndicator = true;
		this.cbxTPCtr2beta.UseUnderline = true;
		this.hbox35.Add(this.cbxTPCtr2beta);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.cbxTPCtr2beta]));
		w33.Position = 1;
		// Container child hbox35.Gtk.Box+BoxChild
		this.cbxTPCTR3 = new global::Gtk.CheckButton();
		this.cbxTPCTR3.CanFocus = true;
		this.cbxTPCTR3.Name = "cbxTPCTR3";
		this.cbxTPCTR3.Label = global::Mono.Unix.Catalog.GetString("Is TR3");
		this.cbxTPCTR3.DrawIndicator = true;
		this.cbxTPCTR3.UseUnderline = true;
		this.hbox35.Add(this.cbxTPCTR3);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.cbxTPCTR3]));
		w34.Position = 2;
		this.vbox20.Add(this.hbox35);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.hbox35]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vbox20.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.cbxTPCLanguage = global::Gtk.ComboBox.NewText();
		this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("English"));
		this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("French"));
		this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("German"));
		this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("American"));
		this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("Japanese"));
		this.cbxTPCLanguage.Name = "cbxTPCLanguage";
		this.table2.Add(this.cbxTPCLanguage);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2[this.cbxTPCLanguage]));
		w36.TopAttach = ((uint)(2));
		w36.BottomAttach = ((uint)(3));
		w36.LeftAttach = ((uint)(1));
		w36.RightAttach = ((uint)(2));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label25 = new global::Gtk.Label();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Cypher byte");
		this.table2.Add(this.label25);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table2[this.label25]));
		w37.TopAttach = ((uint)(1));
		w37.BottomAttach = ((uint)(2));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label26 = new global::Gtk.Label();
		this.label26.Name = "label26";
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Language");
		this.table2.Add(this.label26);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table2[this.label26]));
		w38.TopAttach = ((uint)(2));
		w38.BottomAttach = ((uint)(3));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.lblTPCDesc = new global::Gtk.Label();
		this.lblTPCDesc.Name = "lblTPCDesc";
		this.lblTPCDesc.LabelProp = global::Mono.Unix.Catalog.GetString("Description\n\n256");
		this.lblTPCDesc.Justify = ((global::Gtk.Justification)(1));
		this.table2.Add(this.lblTPCDesc);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table2[this.lblTPCDesc]));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.tbeTPCCypher = new global::TRLevelUtility.TwoBaseEntry();
		this.tbeTPCCypher.Events = ((global::Gdk.EventMask)(256));
		this.tbeTPCCypher.Name = "tbeTPCCypher";
		this.tbeTPCCypher.TheBase = 16;
		this.tbeTPCCypher.Min = 0;
		this.tbeTPCCypher.Max = 255;
		this.tbeTPCCypher.Value = 0;
		this.table2.Add(this.tbeTPCCypher);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table2[this.tbeTPCCypher]));
		w40.TopAttach = ((uint)(1));
		w40.BottomAttach = ((uint)(2));
		w40.LeftAttach = ((uint)(1));
		w40.RightAttach = ((uint)(2));
		w40.XOptions = ((global::Gtk.AttachOptions)(4));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.vbox16 = new global::Gtk.VBox();
		this.vbox16.Name = "vbox16";
		this.vbox16.Spacing = 6;
		// Container child vbox16.Gtk.Box+BoxChild
		this.hbox28 = new global::Gtk.HBox();
		this.hbox28.Name = "hbox28";
		this.hbox28.Spacing = 6;
		// Container child hbox28.Gtk.Box+BoxChild
		this.label24 = new global::Gtk.Label();
		this.label24.Name = "label24";
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Load existing:");
		this.hbox28.Add(this.label24);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.label24]));
		w41.Position = 0;
		w41.Expand = false;
		w41.Fill = false;
		// Container child hbox28.Gtk.Box+BoxChild
		this.cbxTPCLoadDesc = global::Gtk.ComboBox.NewText();
		this.cbxTPCLoadDesc.Name = "cbxTPCLoadDesc";
		this.hbox28.Add(this.cbxTPCLoadDesc);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.cbxTPCLoadDesc]));
		w42.Position = 1;
		this.vbox16.Add(this.hbox28);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.hbox28]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.GtkScrolledWindow12 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow12.Name = "GtkScrolledWindow12";
		this.GtkScrolledWindow12.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow12.Gtk.Container+ContainerChild
		this.tvTPCDesc = new global::Gtk.TextView();
		this.tvTPCDesc.CanFocus = true;
		this.tvTPCDesc.Name = "tvTPCDesc";
		this.GtkScrolledWindow12.Add(this.tvTPCDesc);
		this.vbox16.Add(this.GtkScrolledWindow12);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.GtkScrolledWindow12]));
		w45.Position = 1;
		this.table2.Add(this.vbox16);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox16]));
		w46.LeftAttach = ((uint)(1));
		w46.RightAttach = ((uint)(2));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox20.Add(this.table2);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.table2]));
		w47.Position = 1;
		w47.Expand = false;
		w47.Fill = false;
		this.GtkAlignment35.Add(this.vbox20);
		this.frame5.Add(this.GtkAlignment35);
		this.GtkLabel54 = new global::Gtk.Label();
		this.GtkLabel54.Name = "GtkLabel54";
		this.GtkLabel54.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Script</b>");
		this.GtkLabel54.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel54;
		this.hbox30.Add(this.frame5);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.frame5]));
		w50.Position = 0;
		// Container child hbox30.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment36 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment36.Name = "GtkAlignment36";
		this.GtkAlignment36.LeftPadding = ((uint)(12));
		// Container child GtkAlignment36.Gtk.Container+ContainerChild
		this.larTPCdemolvls = new global::TRLevelUtility.ListAddRem();
		this.larTPCdemolvls.Events = ((global::Gdk.EventMask)(256));
		this.larTPCdemolvls.Name = "larTPCdemolvls";
		this.larTPCdemolvls.HideAddRem = false;
		this.GtkAlignment36.Add(this.larTPCdemolvls);
		this.frame1.Add(this.GtkAlignment36);
		this.GtkLabel55 = new global::Gtk.Label();
		this.GtkLabel55.Name = "GtkLabel55";
		this.GtkLabel55.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Demo levels</b>");
		this.GtkLabel55.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel55;
		this.hbox30.Add(this.frame1);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.frame1]));
		w53.Position = 1;
		this.vbox7.Add(this.hbox30);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox30]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Homogeneous = true;
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment19 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment19.Name = "GtkAlignment19";
		this.GtkAlignment19.LeftPadding = ((uint)(12));
		// Container child GtkAlignment19.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(9)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("First option");
		this.table1.Add(this.label13);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table1[this.label13]));
		w55.XOptions = ((global::Gtk.AttachOptions)(4));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Title replace");
		this.table1.Add(this.label14);
		global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table1[this.label14]));
		w56.TopAttach = ((uint)(1));
		w56.BottomAttach = ((uint)(2));
		w56.XOptions = ((global::Gtk.AttachOptions)(4));
		w56.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("On death in demo mode");
		this.table1.Add(this.label15);
		global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table1[this.label15]));
		w57.TopAttach = ((uint)(2));
		w57.BottomAttach = ((uint)(3));
		w57.XOptions = ((global::Gtk.AttachOptions)(4));
		w57.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("On death in game");
		this.table1.Add(this.label16);
		global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table1[this.label16]));
		w58.TopAttach = ((uint)(3));
		w58.BottomAttach = ((uint)(4));
		w58.XOptions = ((global::Gtk.AttachOptions)(4));
		w58.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("No input time (seconds)");
		this.table1.Add(this.label17);
		global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table1[this.label17]));
		w59.TopAttach = ((uint)(6));
		w59.BottomAttach = ((uint)(7));
		w59.XOptions = ((global::Gtk.AttachOptions)(4));
		w59.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("On demo interrupt");
		this.table1.Add(this.label18);
		global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table1[this.label18]));
		w60.TopAttach = ((uint)(4));
		w60.BottomAttach = ((uint)(5));
		w60.XOptions = ((global::Gtk.AttachOptions)(4));
		w60.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("On demo end");
		this.table1.Add(this.label19);
		global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table1[this.label19]));
		w61.TopAttach = ((uint)(5));
		w61.BottomAttach = ((uint)(6));
		w61.XOptions = ((global::Gtk.AttachOptions)(4));
		w61.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Title soundtrack");
		this.table1.Add(this.label20);
		global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table1[this.label20]));
		w62.TopAttach = ((uint)(7));
		w62.BottomAttach = ((uint)(8));
		w62.XOptions = ((global::Gtk.AttachOptions)(4));
		w62.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("\"found a secret\" soundtrack");
		this.table1.Add(this.label21);
		global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table1[this.label21]));
		w63.TopAttach = ((uint)(8));
		w63.BottomAttach = ((uint)(9));
		w63.XOptions = ((global::Gtk.AttachOptions)(4));
		w63.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tpcFirstOption = new global::TRLevelUtility.ScriptActionWgt();
		this.tpcFirstOption.Events = ((global::Gdk.EventMask)(256));
		this.tpcFirstOption.Name = "tpcFirstOption";
		this.tpcFirstOption.Value = ((uint)(0));
		this.table1.Add(this.tpcFirstOption);
		global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcFirstOption]));
		w64.LeftAttach = ((uint)(1));
		w64.RightAttach = ((uint)(2));
		w64.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tpcNoInputTime = new global::Gtk.SpinButton(0D, 4294967295D, 1D);
		this.tpcNoInputTime.CanFocus = true;
		this.tpcNoInputTime.Name = "tpcNoInputTime";
		this.tpcNoInputTime.Adjustment.PageIncrement = 10D;
		this.tpcNoInputTime.ClimbRate = 1D;
		this.tpcNoInputTime.Numeric = true;
		this.table1.Add(this.tpcNoInputTime);
		global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcNoInputTime]));
		w65.TopAttach = ((uint)(6));
		w65.BottomAttach = ((uint)(7));
		w65.LeftAttach = ((uint)(1));
		w65.RightAttach = ((uint)(2));
		w65.XOptions = ((global::Gtk.AttachOptions)(4));
		w65.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tpcOnDeathDemoMode = new global::TRLevelUtility.ScriptActionWgt();
		this.tpcOnDeathDemoMode.Events = ((global::Gdk.EventMask)(256));
		this.tpcOnDeathDemoMode.Name = "tpcOnDeathDemoMode";
		this.tpcOnDeathDemoMode.Value = ((uint)(0));
		this.table1.Add(this.tpcOnDeathDemoMode);
		global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcOnDeathDemoMode]));
		w66.TopAttach = ((uint)(2));
		w66.BottomAttach = ((uint)(3));
		w66.LeftAttach = ((uint)(1));
		w66.RightAttach = ((uint)(2));
		w66.XOptions = ((global::Gtk.AttachOptions)(4));
		w66.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tpcOnDeathInGame = new global::TRLevelUtility.ScriptActionWgt();
		this.tpcOnDeathInGame.Events = ((global::Gdk.EventMask)(256));
		this.tpcOnDeathInGame.Name = "tpcOnDeathInGame";
		this.tpcOnDeathInGame.Value = ((uint)(0));
		this.table1.Add(this.tpcOnDeathInGame);
		global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcOnDeathInGame]));
		w67.TopAttach = ((uint)(3));
		w67.BottomAttach = ((uint)(4));
		w67.LeftAttach = ((uint)(1));
		w67.RightAttach = ((uint)(2));
		w67.XOptions = ((global::Gtk.AttachOptions)(4));
		w67.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tpcOnDemoEnd = new global::TRLevelUtility.ScriptActionWgt();
		this.tpcOnDemoEnd.Events = ((global::Gdk.EventMask)(256));
		this.tpcOnDemoEnd.Name = "tpcOnDemoEnd";
		this.tpcOnDemoEnd.Value = ((uint)(0));
		this.table1.Add(this.tpcOnDemoEnd);
		global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcOnDemoEnd]));
		w68.TopAttach = ((uint)(5));
		w68.BottomAttach = ((uint)(6));
		w68.LeftAttach = ((uint)(1));
		w68.RightAttach = ((uint)(2));
		w68.XOptions = ((global::Gtk.AttachOptions)(4));
		w68.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tpcOnDemoInterrupt = new global::TRLevelUtility.ScriptActionWgt();
		this.tpcOnDemoInterrupt.Events = ((global::Gdk.EventMask)(256));
		this.tpcOnDemoInterrupt.Name = "tpcOnDemoInterrupt";
		this.tpcOnDemoInterrupt.Value = ((uint)(0));
		this.table1.Add(this.tpcOnDemoInterrupt);
		global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcOnDemoInterrupt]));
		w69.TopAttach = ((uint)(4));
		w69.BottomAttach = ((uint)(5));
		w69.LeftAttach = ((uint)(1));
		w69.RightAttach = ((uint)(2));
		w69.XOptions = ((global::Gtk.AttachOptions)(4));
		w69.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tpcSecretSound = new global::Gtk.SpinButton(0D, 65535D, 1D);
		this.tpcSecretSound.CanFocus = true;
		this.tpcSecretSound.Name = "tpcSecretSound";
		this.tpcSecretSound.Adjustment.PageIncrement = 10D;
		this.tpcSecretSound.ClimbRate = 1D;
		this.tpcSecretSound.Numeric = true;
		this.table1.Add(this.tpcSecretSound);
		global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcSecretSound]));
		w70.TopAttach = ((uint)(8));
		w70.BottomAttach = ((uint)(9));
		w70.LeftAttach = ((uint)(1));
		w70.RightAttach = ((uint)(2));
		w70.XOptions = ((global::Gtk.AttachOptions)(4));
		w70.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tpcTitleReplace = new global::TRLevelUtility.ScriptActionWgt();
		this.tpcTitleReplace.Events = ((global::Gdk.EventMask)(256));
		this.tpcTitleReplace.Name = "tpcTitleReplace";
		this.tpcTitleReplace.Value = ((uint)(0));
		this.table1.Add(this.tpcTitleReplace);
		global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcTitleReplace]));
		w71.TopAttach = ((uint)(1));
		w71.BottomAttach = ((uint)(2));
		w71.LeftAttach = ((uint)(1));
		w71.RightAttach = ((uint)(2));
		w71.XOptions = ((global::Gtk.AttachOptions)(4));
		w71.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tpcTitleSound = new global::Gtk.SpinButton(0D, 65535D, 1D);
		this.tpcTitleSound.CanFocus = true;
		this.tpcTitleSound.Name = "tpcTitleSound";
		this.tpcTitleSound.Adjustment.PageIncrement = 10D;
		this.tpcTitleSound.ClimbRate = 1D;
		this.tpcTitleSound.Numeric = true;
		this.table1.Add(this.tpcTitleSound);
		global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcTitleSound]));
		w72.TopAttach = ((uint)(7));
		w72.BottomAttach = ((uint)(8));
		w72.LeftAttach = ((uint)(1));
		w72.RightAttach = ((uint)(2));
		w72.XOptions = ((global::Gtk.AttachOptions)(4));
		w72.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment19.Add(this.table1);
		this.frame3.Add(this.GtkAlignment19);
		this.GtkLabel22 = new global::Gtk.Label();
		this.GtkLabel22.Name = "GtkLabel22";
		this.GtkLabel22.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Options</b>");
		this.GtkLabel22.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel22;
		this.hbox11.Add(this.frame3);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.frame3]));
		w75.Position = 0;
		// Container child hbox11.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment20 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment20.Name = "GtkAlignment20";
		this.GtkAlignment20.LeftPadding = ((uint)(12));
		// Container child GtkAlignment20.Gtk.Container+ContainerChild
		this.hbox18 = new global::Gtk.HBox();
		this.hbox18.Name = "hbox18";
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.vboxTPCFlags = new global::Gtk.VBox();
		this.vboxTPCFlags.Name = "vboxTPCFlags";
		this.vboxTPCFlags.Spacing = 6;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.tbeTPCFlags = new global::TRLevelUtility.TwoBaseEntry();
		this.tbeTPCFlags.Events = ((global::Gdk.EventMask)(256));
		this.tbeTPCFlags.Name = "tbeTPCFlags";
		this.tbeTPCFlags.TheBase = 2;
		this.tbeTPCFlags.Min = 0;
		this.tbeTPCFlags.Max = 65535;
		this.tbeTPCFlags.Value = 0;
		this.vboxTPCFlags.Add(this.tbeTPCFlags);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.tbeTPCFlags]));
		w76.Position = 0;
		w76.Expand = false;
		w76.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag1 = new global::Gtk.CheckButton();
		this.cbxTPCFlag1.CanFocus = true;
		this.cbxTPCFlag1.Name = "cbxTPCFlag1";
		this.cbxTPCFlag1.Label = global::Mono.Unix.Catalog.GetString("Demo version");
		this.cbxTPCFlag1.DrawIndicator = true;
		this.cbxTPCFlag1.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag1);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag1]));
		w77.Position = 1;
		w77.Expand = false;
		w77.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag2 = new global::Gtk.CheckButton();
		this.cbxTPCFlag2.CanFocus = true;
		this.cbxTPCFlag2.Name = "cbxTPCFlag2";
		this.cbxTPCFlag2.Label = global::Mono.Unix.Catalog.GetString("Title disabled");
		this.cbxTPCFlag2.DrawIndicator = true;
		this.cbxTPCFlag2.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag2);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag2]));
		w78.Position = 2;
		w78.Expand = false;
		w78.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag3 = new global::Gtk.CheckButton();
		this.cbxTPCFlag3.CanFocus = true;
		this.cbxTPCFlag3.Name = "cbxTPCFlag3";
		this.cbxTPCFlag3.Label = global::Mono.Unix.Catalog.GetString("Cheat sequence disabled");
		this.cbxTPCFlag3.DrawIndicator = true;
		this.cbxTPCFlag3.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag3);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag3]));
		w79.Position = 3;
		w79.Expand = false;
		w79.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag4 = new global::Gtk.CheckButton();
		this.cbxTPCFlag4.CanFocus = true;
		this.cbxTPCFlag4.Name = "cbxTPCFlag4";
		this.cbxTPCFlag4.Label = global::Mono.Unix.Catalog.GetString("No input timeout");
		this.cbxTPCFlag4.DrawIndicator = true;
		this.cbxTPCFlag4.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag4);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag4]));
		w80.Position = 4;
		w80.Expand = false;
		w80.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag5 = new global::Gtk.CheckButton();
		this.cbxTPCFlag5.CanFocus = true;
		this.cbxTPCFlag5.Name = "cbxTPCFlag5";
		this.cbxTPCFlag5.Label = global::Mono.Unix.Catalog.GetString("Load/Save disabled");
		this.cbxTPCFlag5.DrawIndicator = true;
		this.cbxTPCFlag5.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag5);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag5]));
		w81.Position = 5;
		w81.Expand = false;
		w81.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag6 = new global::Gtk.CheckButton();
		this.cbxTPCFlag6.CanFocus = true;
		this.cbxTPCFlag6.Name = "cbxTPCFlag6";
		this.cbxTPCFlag6.Label = global::Mono.Unix.Catalog.GetString("Screen sizing keys disabled");
		this.cbxTPCFlag6.DrawIndicator = true;
		this.cbxTPCFlag6.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag6);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag6]));
		w82.Position = 6;
		w82.Expand = false;
		w82.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag7 = new global::Gtk.CheckButton();
		this.cbxTPCFlag7.CanFocus = true;
		this.cbxTPCFlag7.Name = "cbxTPCFlag7";
		this.cbxTPCFlag7.Label = global::Mono.Unix.Catalog.GetString("Lock out option ring");
		this.cbxTPCFlag7.DrawIndicator = true;
		this.cbxTPCFlag7.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag7);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag7]));
		w83.Position = 7;
		w83.Expand = false;
		w83.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag8 = new global::Gtk.CheckButton();
		this.cbxTPCFlag8.CanFocus = true;
		this.cbxTPCFlag8.Name = "cbxTPCFlag8";
		this.cbxTPCFlag8.Label = global::Mono.Unix.Catalog.GetString("DOZY cheat enabled (present, but no effect in-game)");
		this.cbxTPCFlag8.DrawIndicator = true;
		this.cbxTPCFlag8.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag8);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag8]));
		w84.Position = 8;
		w84.Expand = false;
		w84.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag9 = new global::Gtk.CheckButton();
		this.cbxTPCFlag9.CanFocus = true;
		this.cbxTPCFlag9.Name = "cbxTPCFlag9";
		this.cbxTPCFlag9.Label = global::Mono.Unix.Catalog.GetString("Use security tag (encrypt strings using the specified XOR key)");
		this.cbxTPCFlag9.DrawIndicator = true;
		this.cbxTPCFlag9.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag9);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag9]));
		w85.Position = 9;
		w85.Expand = false;
		w85.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag10 = new global::Gtk.CheckButton();
		this.cbxTPCFlag10.CanFocus = true;
		this.cbxTPCFlag10.Name = "cbxTPCFlag10";
		this.cbxTPCFlag10.Label = global::Mono.Unix.Catalog.GetString("Enable gym (usually set, no effect if disabled)");
		this.cbxTPCFlag10.DrawIndicator = true;
		this.cbxTPCFlag10.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag10);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag10]));
		w86.Position = 10;
		w86.Expand = false;
		w86.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag11 = new global::Gtk.CheckButton();
		this.cbxTPCFlag11.CanFocus = true;
		this.cbxTPCFlag11.Name = "cbxTPCFlag11";
		this.cbxTPCFlag11.Label = global::Mono.Unix.Catalog.GetString("Select any level (all levels are listed when choosing \'New Game\')");
		this.cbxTPCFlag11.DrawIndicator = true;
		this.cbxTPCFlag11.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag11);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag11]));
		w87.Position = 11;
		w87.Expand = false;
		w87.Fill = false;
		// Container child vboxTPCFlags.Gtk.Box+BoxChild
		this.cbxTPCFlag12 = new global::Gtk.CheckButton();
		this.cbxTPCFlag12.CanFocus = true;
		this.cbxTPCFlag12.Name = "cbxTPCFlag12";
		this.cbxTPCFlag12.Label = global::Mono.Unix.Catalog.GetString("Enable cheat code (no apparent effect)");
		this.cbxTPCFlag12.DrawIndicator = true;
		this.cbxTPCFlag12.UseUnderline = true;
		this.vboxTPCFlags.Add(this.cbxTPCFlag12);
		global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag12]));
		w88.Position = 12;
		w88.Expand = false;
		w88.Fill = false;
		this.hbox18.Add(this.vboxTPCFlags);
		global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.vboxTPCFlags]));
		w89.Position = 0;
		this.GtkAlignment20.Add(this.hbox18);
		this.frame4.Add(this.GtkAlignment20);
		this.GtkLabel35 = new global::Gtk.Label();
		this.GtkLabel35.Name = "GtkLabel35";
		this.GtkLabel35.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Flags</b>");
		this.GtkLabel35.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel35;
		this.hbox11.Add(this.frame4);
		global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.frame4]));
		w92.Position = 1;
		this.vbox7.Add(this.hbox11);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox11]));
		w93.Position = 1;
		this.notebook2.Add(this.vbox7);
		global::Gtk.Notebook.NotebookChild w94 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.vbox7]));
		w94.Position = 2;
		// Notebook tab
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Options");
		this.notebook2.SetTabLabel(this.vbox7, this.label10);
		this.label10.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.hbox32 = new global::Gtk.HBox();
		this.hbox32.Name = "hbox32";
		this.hbox32.Spacing = 6;
		// Container child hbox32.Gtk.Box+BoxChild
		this.frame7 = new global::Gtk.Frame();
		this.frame7.Name = "frame7";
		this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame7.Gtk.Container+ContainerChild
		this.GtkAlignment43 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment43.Name = "GtkAlignment43";
		this.GtkAlignment43.LeftPadding = ((uint)(12));
		// Container child GtkAlignment43.Gtk.Container+ContainerChild
		this.larTPCscSlots = new global::TRLevelUtility.ListAddRem();
		this.larTPCscSlots.Events = ((global::Gdk.EventMask)(256));
		this.larTPCscSlots.Name = "larTPCscSlots";
		this.larTPCscSlots.HideAddRem = false;
		this.GtkAlignment43.Add(this.larTPCscSlots);
		this.frame7.Add(this.GtkAlignment43);
		this.GtkLabel62 = new global::Gtk.Label();
		this.GtkLabel62.Name = "GtkLabel62";
		this.GtkLabel62.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Script slots</b>");
		this.GtkLabel62.UseMarkup = true;
		this.frame7.LabelWidget = this.GtkLabel62;
		this.hbox32.Add(this.frame7);
		global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.frame7]));
		w97.Position = 0;
		w97.Expand = false;
		w97.Fill = false;
		// Container child hbox32.Gtk.Box+BoxChild
		this.vbox21 = new global::Gtk.VBox();
		this.vbox21.Name = "vbox21";
		this.vbox21.Spacing = 6;
		// Container child vbox21.Gtk.Box+BoxChild
		this.frame8 = new global::Gtk.Frame();
		this.frame8.Name = "frame8";
		this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame8.Gtk.Container+ContainerChild
		this.GtkAlignment44 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment44.Name = "GtkAlignment44";
		this.GtkAlignment44.LeftPadding = ((uint)(12));
		// Container child GtkAlignment44.Gtk.Container+ContainerChild
		this.larTPCscCommands = new global::TRLevelUtility.ListAddRem();
		this.larTPCscCommands.Events = ((global::Gdk.EventMask)(256));
		this.larTPCscCommands.Name = "larTPCscCommands";
		this.larTPCscCommands.HideAddRem = false;
		this.GtkAlignment44.Add(this.larTPCscCommands);
		this.frame8.Add(this.GtkAlignment44);
		this.GtkLabel63 = new global::Gtk.Label();
		this.GtkLabel63.Name = "GtkLabel63";
		this.GtkLabel63.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Script commands</b>");
		this.GtkLabel63.UseMarkup = true;
		this.frame8.LabelWidget = this.GtkLabel63;
		this.vbox21.Add(this.frame8);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.frame8]));
		w100.Position = 0;
		// Container child vbox21.Gtk.Box+BoxChild
		this.frame9 = new global::Gtk.Frame();
		this.frame9.Name = "frame9";
		this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame9.Gtk.Container+ContainerChild
		this.GtkAlignment45 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment45.Name = "GtkAlignment45";
		this.GtkAlignment45.LeftPadding = ((uint)(12));
		// Container child GtkAlignment45.Gtk.Container+ContainerChild
		this.table4 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.cbxTPCCommand = global::Gtk.ComboBox.NewText();
		this.cbxTPCCommand.Sensitive = false;
		this.cbxTPCCommand.Name = "cbxTPCCommand";
		this.table4.Add(this.cbxTPCCommand);
		global::Gtk.Table.TableChild w101 = ((global::Gtk.Table.TableChild)(this.table4[this.cbxTPCCommand]));
		w101.LeftAttach = ((uint)(1));
		w101.RightAttach = ((uint)(2));
		w101.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Command");
		this.table4.Add(this.label23);
		global::Gtk.Table.TableChild w102 = ((global::Gtk.Table.TableChild)(this.table4[this.label23]));
		w102.XOptions = ((global::Gtk.AttachOptions)(4));
		w102.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.lblTPCcmdHelp = new global::Gtk.Label();
		this.lblTPCcmdHelp.Name = "lblTPCcmdHelp";
		this.table4.Add(this.lblTPCcmdHelp);
		global::Gtk.Table.TableChild w103 = ((global::Gtk.Table.TableChild)(this.table4[this.lblTPCcmdHelp]));
		w103.TopAttach = ((uint)(1));
		w103.BottomAttach = ((uint)(2));
		w103.LeftAttach = ((uint)(1));
		w103.RightAttach = ((uint)(2));
		w103.XOptions = ((global::Gtk.AttachOptions)(4));
		w103.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.lblTPCoperandName = new global::Gtk.Label();
		this.lblTPCoperandName.Name = "lblTPCoperandName";
		this.lblTPCoperandName.LabelProp = global::Mono.Unix.Catalog.GetString("Operand");
		this.table4.Add(this.lblTPCoperandName);
		global::Gtk.Table.TableChild w104 = ((global::Gtk.Table.TableChild)(this.table4[this.lblTPCoperandName]));
		w104.TopAttach = ((uint)(2));
		w104.BottomAttach = ((uint)(3));
		w104.XOptions = ((global::Gtk.AttachOptions)(4));
		w104.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.sbTPCOperand = new global::Gtk.SpinButton(0D, 65535D, 1D);
		this.sbTPCOperand.Sensitive = false;
		this.sbTPCOperand.CanFocus = true;
		this.sbTPCOperand.Name = "sbTPCOperand";
		this.sbTPCOperand.Adjustment.PageIncrement = 10D;
		this.sbTPCOperand.ClimbRate = 1D;
		this.sbTPCOperand.Numeric = true;
		this.table4.Add(this.sbTPCOperand);
		global::Gtk.Table.TableChild w105 = ((global::Gtk.Table.TableChild)(this.table4[this.sbTPCOperand]));
		w105.TopAttach = ((uint)(2));
		w105.BottomAttach = ((uint)(3));
		w105.LeftAttach = ((uint)(1));
		w105.RightAttach = ((uint)(2));
		w105.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment45.Add(this.table4);
		this.frame9.Add(this.GtkAlignment45);
		this.GtkLabel64 = new global::Gtk.Label();
		this.GtkLabel64.Name = "GtkLabel64";
		this.GtkLabel64.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Command options</b>");
		this.GtkLabel64.UseMarkup = true;
		this.frame9.LabelWidget = this.GtkLabel64;
		this.vbox21.Add(this.frame9);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.frame9]));
		w108.Position = 1;
		w108.Expand = false;
		w108.Fill = false;
		this.hbox32.Add(this.vbox21);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.vbox21]));
		w109.Position = 1;
		this.notebook2.Add(this.hbox32);
		global::Gtk.Notebook.NotebookChild w110 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.hbox32]));
		w110.Position = 3;
		// Notebook tab
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Script");
		this.notebook2.SetTabLabel(this.hbox32, this.label11);
		this.label11.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.notebook3 = new global::Gtk.Notebook();
		this.notebook3.CanFocus = true;
		this.notebook3.Name = "notebook3";
		this.notebook3.CurrentPage = 1;
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.larTPCgs = new global::TRLevelUtility.ListAddRem();
		this.larTPCgs.Events = ((global::Gdk.EventMask)(256));
		this.larTPCgs.Name = "larTPCgs";
		this.larTPCgs.HideAddRem = false;
		this.notebook3.Add(this.larTPCgs);
		// Notebook tab
		this.label27 = new global::Gtk.Label();
		this.label27.Name = "label27";
		this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Game strings");
		this.notebook3.SetTabLabel(this.larTPCgs, this.label27);
		this.label27.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.larTPCps = new global::TRLevelUtility.ListAddRem();
		this.larTPCps.Events = ((global::Gdk.EventMask)(256));
		this.larTPCps.Name = "larTPCps";
		this.larTPCps.HideAddRem = false;
		this.notebook3.Add(this.larTPCps);
		global::Gtk.Notebook.NotebookChild w112 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCps]));
		w112.Position = 1;
		// Notebook tab
		this.label29 = new global::Gtk.Label();
		this.label29.Name = "label29";
		this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("PC strings");
		this.notebook3.SetTabLabel(this.larTPCps, this.label29);
		this.label29.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.larTPCpss = new global::TRLevelUtility.ListAddRem();
		this.larTPCpss.Events = ((global::Gdk.EventMask)(256));
		this.larTPCpss.Name = "larTPCpss";
		this.larTPCpss.HideAddRem = false;
		this.notebook3.Add(this.larTPCpss);
		global::Gtk.Notebook.NotebookChild w113 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCpss]));
		w113.Position = 2;
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("PSX strings");
		this.notebook3.SetTabLabel(this.larTPCpss, this.label2);
		this.label2.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.larTPCPuzzle = new global::TRLevelUtility.ListAddRem();
		this.larTPCPuzzle.Events = ((global::Gdk.EventMask)(256));
		this.larTPCPuzzle.Name = "larTPCPuzzle";
		this.larTPCPuzzle.HideAddRem = false;
		this.notebook3.Add(this.larTPCPuzzle);
		global::Gtk.Notebook.NotebookChild w114 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCPuzzle]));
		w114.Position = 3;
		// Notebook tab
		this.label31 = new global::Gtk.Label();
		this.label31.Name = "label31";
		this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Puzzle");
		this.notebook3.SetTabLabel(this.larTPCPuzzle, this.label31);
		this.label31.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.larTPCPickups = new global::TRLevelUtility.ListAddRem();
		this.larTPCPickups.Events = ((global::Gdk.EventMask)(256));
		this.larTPCPickups.Name = "larTPCPickups";
		this.larTPCPickups.HideAddRem = false;
		this.notebook3.Add(this.larTPCPickups);
		global::Gtk.Notebook.NotebookChild w115 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCPickups]));
		w115.Position = 4;
		// Notebook tab
		this.label36 = new global::Gtk.Label();
		this.label36.Name = "label36";
		this.label36.LabelProp = global::Mono.Unix.Catalog.GetString("Pickups");
		this.notebook3.SetTabLabel(this.larTPCPickups, this.label36);
		this.label36.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.larTPCKeys = new global::TRLevelUtility.ListAddRem();
		this.larTPCKeys.Events = ((global::Gdk.EventMask)(256));
		this.larTPCKeys.Name = "larTPCKeys";
		this.larTPCKeys.HideAddRem = true;
		this.notebook3.Add(this.larTPCKeys);
		global::Gtk.Notebook.NotebookChild w116 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCKeys]));
		w116.Position = 5;
		// Notebook tab
		this.label37 = new global::Gtk.Label();
		this.label37.Name = "label37";
		this.label37.LabelProp = global::Mono.Unix.Catalog.GetString("Keys");
		this.notebook3.SetTabLabel(this.larTPCKeys, this.label37);
		this.label37.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.larTPCSecrets = new global::TRLevelUtility.ListAddRem();
		this.larTPCSecrets.Events = ((global::Gdk.EventMask)(256));
		this.larTPCSecrets.Name = "larTPCSecrets";
		this.larTPCSecrets.HideAddRem = false;
		this.notebook3.Add(this.larTPCSecrets);
		global::Gtk.Notebook.NotebookChild w117 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCSecrets]));
		w117.Position = 6;
		// Notebook tab
		this.label28 = new global::Gtk.Label();
		this.label28.Name = "label28";
		this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("Secrets");
		this.notebook3.SetTabLabel(this.larTPCSecrets, this.label28);
		this.label28.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.larTPCSpecial = new global::TRLevelUtility.ListAddRem();
		this.larTPCSpecial.Events = ((global::Gdk.EventMask)(256));
		this.larTPCSpecial.Name = "larTPCSpecial";
		this.larTPCSpecial.HideAddRem = false;
		this.notebook3.Add(this.larTPCSpecial);
		global::Gtk.Notebook.NotebookChild w118 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCSpecial]));
		w118.Position = 7;
		// Notebook tab
		this.label38 = new global::Gtk.Label();
		this.label38.Name = "label38";
		this.label38.LabelProp = global::Mono.Unix.Catalog.GetString("Special");
		this.notebook3.SetTabLabel(this.larTPCSpecial, this.label38);
		this.label38.ShowAll();
		this.notebook2.Add(this.notebook3);
		global::Gtk.Notebook.NotebookChild w119 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.notebook3]));
		w119.Position = 4;
		// Notebook tab
		this.label32 = new global::Gtk.Label();
		this.label32.Name = "label32";
		this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("Strings");
		this.notebook2.SetTabLabel(this.notebook3, this.label32);
		this.label32.ShowAll();
		this.notebook1.Add(this.notebook2);
		global::Gtk.Notebook.NotebookChild w120 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.notebook2]));
		w120.Position = 1;
		// Notebook tab
		this.label33 = new global::Gtk.Label();
		this.label33.Name = "label33";
		this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("Script TOMBPC");
		this.notebook1.SetTabLabel(this.notebook2, this.label33);
		this.label33.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox27 = new global::Gtk.VBox();
		this.vbox27.Name = "vbox27";
		this.vbox27.Spacing = 6;
		// Container child vbox27.Gtk.Box+BoxChild
		this.hbox46 = new global::Gtk.HBox();
		this.hbox46.Name = "hbox46";
		this.hbox46.Spacing = 6;
		// Container child hbox46.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment56 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment56.Name = "GtkAlignment56";
		this.GtkAlignment56.LeftPadding = ((uint)(12));
		// Container child GtkAlignment56.Gtk.Container+ContainerChild
		this.hbox43 = new global::Gtk.HBox();
		this.hbox43.Name = "hbox43";
		this.hbox43.Spacing = 6;
		// Container child hbox43.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("XOR key (unused)");
		this.table3.Add(this.label12);
		global::Gtk.Table.TableChild w121 = ((global::Gtk.Table.TableChild)(this.table3[this.label12]));
		w121.TopAttach = ((uint)(1));
		w121.BottomAttach = ((uint)(2));
		w121.XOptions = ((global::Gtk.AttachOptions)(4));
		w121.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Input timeout (seconds)");
		this.table3.Add(this.label7);
		global::Gtk.Table.TableChild w122 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
		w122.XOptions = ((global::Gtk.AttachOptions)(4));
		w122.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.sbTR4InputTimeout = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.sbTR4InputTimeout.CanFocus = true;
		this.sbTR4InputTimeout.Name = "sbTR4InputTimeout";
		this.sbTR4InputTimeout.Adjustment.PageIncrement = 10D;
		this.sbTR4InputTimeout.ClimbRate = 1D;
		this.sbTR4InputTimeout.Numeric = true;
		this.table3.Add(this.sbTR4InputTimeout);
		global::Gtk.Table.TableChild w123 = ((global::Gtk.Table.TableChild)(this.table3[this.sbTR4InputTimeout]));
		w123.LeftAttach = ((uint)(1));
		w123.RightAttach = ((uint)(2));
		w123.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.tbeTR4Security = new global::TRLevelUtility.TwoBaseEntry();
		this.tbeTR4Security.Events = ((global::Gdk.EventMask)(256));
		this.tbeTR4Security.Name = "tbeTR4Security";
		this.tbeTR4Security.TheBase = 16;
		this.tbeTR4Security.Min = 0;
		this.tbeTR4Security.Max = 255;
		this.tbeTR4Security.Value = 0;
		this.table3.Add(this.tbeTR4Security);
		global::Gtk.Table.TableChild w124 = ((global::Gtk.Table.TableChild)(this.table3[this.tbeTR4Security]));
		w124.TopAttach = ((uint)(1));
		w124.BottomAttach = ((uint)(2));
		w124.LeftAttach = ((uint)(1));
		w124.RightAttach = ((uint)(2));
		w124.XOptions = ((global::Gtk.AttachOptions)(4));
		w124.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox43.Add(this.table3);
		global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.hbox43[this.table3]));
		w125.Position = 0;
		this.GtkAlignment56.Add(this.hbox43);
		this.frame2.Add(this.GtkAlignment56);
		this.GtkLabel72 = new global::Gtk.Label();
		this.GtkLabel72.Name = "GtkLabel72";
		this.GtkLabel72.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Options</b>");
		this.GtkLabel72.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel72;
		this.hbox46.Add(this.frame2);
		global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.hbox46[this.frame2]));
		w128.Position = 0;
		// Container child hbox46.Gtk.Box+BoxChild
		this.frame6 = new global::Gtk.Frame();
		this.frame6.Name = "frame6";
		this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame6.Gtk.Container+ContainerChild
		this.GtkAlignment57 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment57.Name = "GtkAlignment57";
		this.GtkAlignment57.LeftPadding = ((uint)(12));
		// Container child GtkAlignment57.Gtk.Container+ContainerChild
		this.vboxTR4Flags = new global::Gtk.VBox();
		this.vboxTR4Flags.Name = "vboxTR4Flags";
		this.vboxTR4Flags.Spacing = 6;
		// Container child vboxTR4Flags.Gtk.Box+BoxChild
		this.tbeTR4Flags = new global::TRLevelUtility.TwoBaseEntry();
		this.tbeTR4Flags.Events = ((global::Gdk.EventMask)(256));
		this.tbeTR4Flags.Name = "tbeTR4Flags";
		this.tbeTR4Flags.TheBase = 2;
		this.tbeTR4Flags.Min = 0;
		this.tbeTR4Flags.Max = 255;
		this.tbeTR4Flags.Value = 0;
		this.vboxTR4Flags.Add(this.tbeTR4Flags);
		global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.vboxTR4Flags[this.tbeTR4Flags]));
		w129.Position = 0;
		w129.Expand = false;
		w129.Fill = false;
		// Container child vboxTR4Flags.Gtk.Box+BoxChild
		this.hboxTR4Flags = new global::Gtk.HBox();
		this.hboxTR4Flags.Name = "hboxTR4Flags";
		this.hboxTR4Flags.Spacing = 6;
		// Container child hboxTR4Flags.Gtk.Box+BoxChild
		this.cbxTR4Flag1 = new global::Gtk.CheckButton();
		this.cbxTR4Flag1.CanFocus = true;
		this.cbxTR4Flag1.Name = "cbxTR4Flag1";
		this.cbxTR4Flag1.Label = global::Mono.Unix.Catalog.GetString("DOZY enabled");
		this.cbxTR4Flag1.DrawIndicator = true;
		this.cbxTR4Flag1.UseUnderline = true;
		this.hboxTR4Flags.Add(this.cbxTR4Flag1);
		global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag1]));
		w130.Position = 0;
		// Container child hboxTR4Flags.Gtk.Box+BoxChild
		this.cbxTR4Flag2 = new global::Gtk.CheckButton();
		this.cbxTR4Flag2.CanFocus = true;
		this.cbxTR4Flag2.Name = "cbxTR4Flag2";
		this.cbxTR4Flag2.Label = global::Mono.Unix.Catalog.GetString("Load/Save enabled");
		this.cbxTR4Flag2.DrawIndicator = true;
		this.cbxTR4Flag2.UseUnderline = true;
		this.hboxTR4Flags.Add(this.cbxTR4Flag2);
		global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag2]));
		w131.Position = 1;
		// Container child hboxTR4Flags.Gtk.Box+BoxChild
		this.cbxTR4Flag3 = new global::Gtk.CheckButton();
		this.cbxTR4Flag3.CanFocus = true;
		this.cbxTR4Flag3.Name = "cbxTR4Flag3";
		this.cbxTR4Flag3.Label = global::Mono.Unix.Catalog.GetString("Display title screen");
		this.cbxTR4Flag3.DrawIndicator = true;
		this.cbxTR4Flag3.UseUnderline = true;
		this.hboxTR4Flags.Add(this.cbxTR4Flag3);
		global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag3]));
		w132.Position = 2;
		// Container child hboxTR4Flags.Gtk.Box+BoxChild
		this.cbxTR4Flag4 = new global::Gtk.CheckButton();
		this.cbxTR4Flag4.CanFocus = true;
		this.cbxTR4Flag4.Name = "cbxTR4Flag4";
		this.cbxTR4Flag4.Label = global::Mono.Unix.Catalog.GetString("Select any level");
		this.cbxTR4Flag4.DrawIndicator = true;
		this.cbxTR4Flag4.UseUnderline = true;
		this.hboxTR4Flags.Add(this.cbxTR4Flag4);
		global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag4]));
		w133.Position = 3;
		// Container child hboxTR4Flags.Gtk.Box+BoxChild
		this.cbxTR4Flag8 = new global::Gtk.CheckButton();
		this.cbxTR4Flag8.CanFocus = true;
		this.cbxTR4Flag8.Name = "cbxTR4Flag8";
		this.cbxTR4Flag8.Label = global::Mono.Unix.Catalog.GetString("Demo version (no effect)");
		this.cbxTR4Flag8.DrawIndicator = true;
		this.cbxTR4Flag8.UseUnderline = true;
		this.hboxTR4Flags.Add(this.cbxTR4Flag8);
		global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag8]));
		w134.Position = 4;
		this.vboxTR4Flags.Add(this.hboxTR4Flags);
		global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.vboxTR4Flags[this.hboxTR4Flags]));
		w135.Position = 1;
		w135.Expand = false;
		w135.Fill = false;
		this.GtkAlignment57.Add(this.vboxTR4Flags);
		this.frame6.Add(this.GtkAlignment57);
		this.GtkLabel75 = new global::Gtk.Label();
		this.GtkLabel75.Name = "GtkLabel75";
		this.GtkLabel75.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Flags</b>");
		this.GtkLabel75.UseMarkup = true;
		this.frame6.LabelWidget = this.GtkLabel75;
		this.hbox46.Add(this.frame6);
		global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.hbox46[this.frame6]));
		w138.Position = 1;
		w138.Expand = false;
		w138.Fill = false;
		this.vbox27.Add(this.hbox46);
		global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.hbox46]));
		w139.Position = 0;
		w139.Expand = false;
		w139.Fill = false;
		// Container child vbox27.Gtk.Box+BoxChild
		this.notebook4 = new global::Gtk.Notebook();
		this.notebook4.CanFocus = true;
		this.notebook4.Name = "notebook4";
		this.notebook4.CurrentPage = 1;
		// Container child notebook4.Gtk.Notebook+NotebookChild
		this.hbox47 = new global::Gtk.HBox();
		this.hbox47.Name = "hbox47";
		this.hbox47.Spacing = 6;
		// Container child hbox47.Gtk.Box+BoxChild
		this.GtkScrolledWindow23 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow23.Name = "GtkScrolledWindow23";
		this.GtkScrolledWindow23.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow23.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow23.Add(this.nodeview1);
		this.hbox47.Add(this.GtkScrolledWindow23);
		global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.GtkScrolledWindow23]));
		w141.Position = 0;
		this.notebook4.Add(this.hbox47);
		// Notebook tab
		this.label30 = new global::Gtk.Label();
		this.label30.Name = "label30";
		this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Levels");
		this.notebook4.SetTabLabel(this.hbox47, this.label30);
		this.label30.ShowAll();
		// Notebook tab
		global::Gtk.Label w143 = new global::Gtk.Label();
		w143.Visible = true;
		this.notebook4.Add(w143);
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Strings");
		this.notebook4.SetTabLabel(w143, this.label22);
		this.label22.ShowAll();
		this.vbox27.Add(this.notebook4);
		global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.notebook4]));
		w144.Position = 1;
		this.notebook1.Add(this.vbox27);
		global::Gtk.Notebook.NotebookChild w145 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox27]));
		w145.Position = 2;
		// Notebook tab
		this.label34 = new global::Gtk.Label();
		this.label34.Name = "label34";
		this.label34.LabelProp = global::Mono.Unix.Catalog.GetString("Script TR4");
		this.notebook1.SetTabLabel(this.vbox27, this.label34);
		this.label34.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.notebook1.Add(this.fixed1);
		global::Gtk.Notebook.NotebookChild w146 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.fixed1]));
		w146.Position = 3;
		// Notebook tab
		this.label35 = new global::Gtk.Label();
		this.label35.Name = "label35";
		this.label35.LabelProp = global::Mono.Unix.Catalog.GetString("Level");
		this.notebook1.SetTabLabel(this.fixed1, this.label35);
		this.label35.ShowAll();
		this.vbox1.Add(this.notebook1);
		global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
		w147.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.btnSave.Hide();
		this.btnSaveAs.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnAbout.Clicked += new global::System.EventHandler(this.OnBtnAboutClicked);
		this.btnNewScriptTPC.Clicked += new global::System.EventHandler(this.OnBtnNewScriptTPCClicked);
		this.btnNewScriptTR4.Clicked += new global::System.EventHandler(this.OnBtnNewScriptTR4Clicked);
		this.btnOpenScript.Clicked += new global::System.EventHandler(this.OnBtnOpenScriptClicked);
		this.notebook2.SwitchPage += new global::Gtk.SwitchPageHandler(this.OnNotebook2SwitchPage);
		this.larLevels.RowAdded += new global::TRLevelUtility.ListAddRem.RowAddedHdlr(this.OnLarLevelsRowAdded);
		this.larLevels.RowRemoved += new global::TRLevelUtility.ListAddRem.RowRemovedHdlr(this.OnLarLevelsRowRemoved);
		this.larLevels.RowEdited += new global::TRLevelUtility.ListAddRem.RowEditedHdlr(this.OnLarLevelsRowEdited);
		this.cbxTPCPSX.Toggled += new global::System.EventHandler(this.OnCbxTPCPSXToggled);
		this.cbxTPCtr2beta.Toggled += new global::System.EventHandler(this.OnCbxTPCtr2betaToggled);
		this.cbxTPCTR3.Toggled += new global::System.EventHandler(this.OnCbxTPCTR3Toggled);
		this.cbxTPCLoadDesc.Changed += new global::System.EventHandler(this.OnCbxTPCLoadDescChanged);
		this.tbeTPCFlags.Changed += new global::System.EventHandler(this.OnTbeTPCFlagsChanged);
		this.cbxTPCFlag1.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag2.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag3.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag4.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag5.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag6.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag7.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag8.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag9.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag10.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag11.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.cbxTPCFlag12.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		this.larTPCscSlots.SelectionChanged += new global::TRLevelUtility.ListAddRem.EmptyHdlr(this.OnLarTPCscSlotsSelectionChanged);
		this.larTPCscCommands.SelectionChanged += new global::TRLevelUtility.ListAddRem.EmptyHdlr(this.OnLarTPCscCommandsSelectionChanged);
		this.larTPCscCommands.RowAdded += new global::TRLevelUtility.ListAddRem.RowAddedHdlr(this.OnLarTPCscCommandsRowAdded);
		this.larTPCscCommands.RowRemoved += new global::TRLevelUtility.ListAddRem.RowRemovedHdlr(this.OnLarTPCscCommandsRowRemoved);
		this.sbTPCOperand.Output += new global::Gtk.OutputHandler(this.OnSbTPCOperandOutput);
		this.sbTPCOperand.ValueChanged += new global::System.EventHandler(this.OnSbTPCOperandValueChanged);
		this.cbxTPCCommand.Changed += new global::System.EventHandler(this.OnCbxTPCCommandChanged);
		this.tbeTR4Flags.Changed += new global::System.EventHandler(this.OnTbeTR4FlagsChanged);
		this.cbxTR4Flag1.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
		this.cbxTR4Flag2.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
		this.cbxTR4Flag3.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
		this.cbxTR4Flag4.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
		this.cbxTR4Flag8.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
	}
}
