
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Fixed fixed3;

	private global::Gtk.Button btnSave;

	private global::Gtk.Button btnSaveAs;

	private global::Gtk.Button btnPrefs;

	private global::Gtk.Button btnAbout;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.VBox vbox30;

	private global::Gtk.Label label45;

	private global::Gtk.Label lblVersion;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label5;

	private global::Gtk.Button btnOpenScript;

	private global::Gtk.Button btnNewScriptTR4;

	private global::Gtk.Button btnNewScriptTPC;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label6;

	private global::Gtk.Button btnOpenLvl;

	private global::Gtk.Button btnNewLevel;

	private global::Gtk.VBox vbox31;

	private global::Gtk.Label label46;

	private global::Gtk.ComboBox combobox3;

	private global::Gtk.ComboBoxEntry comboboxentry1;

	private global::Gtk.Label label1;

	private global::TRLevelUtility.PgTPCScript pgtpcscript;

	private global::Gtk.Label label33;

	private global::TRLevelUtility.PgTR4Script pgtr4script;

	private global::Gtk.Label label43;

	private global::Gtk.Label label44;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("TRLevelUtility");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(10));
		this.DefaultWidth = 1060;
		this.DefaultHeight = 760;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.hbox1.BorderWidth = ((uint)(3));
		// Container child hbox1.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox1.Add(this.fixed3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed3]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSave = new global::Gtk.Button();
		this.btnSave.CanFocus = true;
		this.btnSave.Name = "btnSave";
		this.btnSave.UseUnderline = true;
		this.btnSave.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnSave.Label = global::Mono.Unix.Catalog.GetString("_Save");
		global::Gtk.Image w2 = new global::Gtk.Image();
		w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.LargeToolbar);
		this.btnSave.Image = w2;
		this.hbox1.Add(this.btnSave);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSave]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSaveAs = new global::Gtk.Button();
		this.btnSaveAs.CanFocus = true;
		this.btnSaveAs.Name = "btnSaveAs";
		this.btnSaveAs.UseUnderline = true;
		this.btnSaveAs.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnSaveAs.Label = global::Mono.Unix.Catalog.GetString("Save _As");
		global::Gtk.Image w4 = new global::Gtk.Image();
		w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save-as", global::Gtk.IconSize.LargeToolbar);
		this.btnSaveAs.Image = w4;
		this.hbox1.Add(this.btnSaveAs);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSaveAs]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnPrefs = new global::Gtk.Button();
		this.btnPrefs.CanFocus = true;
		this.btnPrefs.Name = "btnPrefs";
		this.btnPrefs.UseUnderline = true;
		this.btnPrefs.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnPrefs.Label = global::Mono.Unix.Catalog.GetString("_Preferences");
		global::Gtk.Image w6 = new global::Gtk.Image();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-preferences", global::Gtk.IconSize.LargeToolbar);
		this.btnPrefs.Image = w6;
		this.hbox1.Add(this.btnPrefs);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnPrefs]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnAbout = new global::Gtk.Button();
		this.btnAbout.CanFocus = true;
		this.btnAbout.Name = "btnAbout";
		this.btnAbout.UseUnderline = true;
		this.btnAbout.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnAbout.Label = global::Mono.Unix.Catalog.GetString("_About");
		global::Gtk.Image w8 = new global::Gtk.Image();
		w8.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-about", global::Gtk.IconSize.LargeToolbar);
		this.btnAbout.Image = w8;
		this.hbox1.Add(this.btnAbout);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnAbout]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		this.notebook1.ShowBorder = false;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 32;
		this.vbox2.BorderWidth = ((uint)(12));
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox30 = new global::Gtk.VBox();
		this.vbox30.Name = "vbox30";
		this.vbox30.Spacing = 6;
		// Container child vbox30.Gtk.Box+BoxChild
		this.label45 = new global::Gtk.Label();
		this.label45.Name = "label45";
		this.label45.LabelProp = global::Mono.Unix.Catalog.GetString("<big><big><big><big>TRLevelUtility</big></big></big></big>");
		this.label45.UseMarkup = true;
		this.vbox30.Add(this.label45);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.label45]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox30.Gtk.Box+BoxChild
		this.lblVersion = new global::Gtk.Label();
		this.lblVersion.Name = "lblVersion";
		this.lblVersion.LabelProp = global::Mono.Unix.Catalog.GetString("version ");
		this.vbox30.Add(this.lblVersion);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.lblVersion]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox2.Add(this.vbox30);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox30]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Script file\nSupported formats: TR2-3 (TOMBPC.DAT), TR4-5 (SCRIPT.DAT)\nAlso suppor" +
				"ts uncompiled TXT script");
		this.hbox2.Add(this.label5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label5]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnOpenScript = new global::Gtk.Button();
		this.btnOpenScript.CanFocus = true;
		this.btnOpenScript.Name = "btnOpenScript";
		this.btnOpenScript.UseUnderline = true;
		this.btnOpenScript.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnOpenScript.Label = global::Mono.Unix.Catalog.GetString("_Open");
		global::Gtk.Image w15 = new global::Gtk.Image();
		w15.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.LargeToolbar);
		this.btnOpenScript.Image = w15;
		this.hbox2.Add(this.btnOpenScript);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnOpenScript]));
		w16.PackType = ((global::Gtk.PackType)(1));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnNewScriptTR4 = new global::Gtk.Button();
		this.btnNewScriptTR4.CanFocus = true;
		this.btnNewScriptTR4.Name = "btnNewScriptTR4";
		this.btnNewScriptTR4.UseUnderline = true;
		this.btnNewScriptTR4.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnNewScriptTR4.Label = global::Mono.Unix.Catalog.GetString("_New TR4-5 script");
		global::Gtk.Image w17 = new global::Gtk.Image();
		w17.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-new", global::Gtk.IconSize.LargeToolbar);
		this.btnNewScriptTR4.Image = w17;
		this.hbox2.Add(this.btnNewScriptTR4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnNewScriptTR4]));
		w18.PackType = ((global::Gtk.PackType)(1));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnNewScriptTPC = new global::Gtk.Button();
		this.btnNewScriptTPC.CanFocus = true;
		this.btnNewScriptTPC.Name = "btnNewScriptTPC";
		this.btnNewScriptTPC.UseUnderline = true;
		this.btnNewScriptTPC.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnNewScriptTPC.Label = global::Mono.Unix.Catalog.GetString("New _TR2-3 script");
		global::Gtk.Image w19 = new global::Gtk.Image();
		w19.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-new", global::Gtk.IconSize.LargeToolbar);
		this.btnNewScriptTPC.Image = w19;
		this.hbox2.Add(this.btnNewScriptTPC);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnNewScriptTPC]));
		w20.PackType = ((global::Gtk.PackType)(1));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Level file\nSupported formats: TR1 (.PHD, .TUB), TR2-3 (.TR2), TR4 (.TR4), TR5 (.T" +
				"RC)\nSupports converting levels between versions and platforms (PC/PSX)");
		this.hbox3.Add(this.label6);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label6]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnOpenLvl = new global::Gtk.Button();
		this.btnOpenLvl.CanFocus = true;
		this.btnOpenLvl.Name = "btnOpenLvl";
		this.btnOpenLvl.UseUnderline = true;
		this.btnOpenLvl.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnOpenLvl.Label = global::Mono.Unix.Catalog.GetString("_Open");
		global::Gtk.Image w23 = new global::Gtk.Image();
		w23.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.LargeToolbar);
		this.btnOpenLvl.Image = w23;
		this.hbox3.Add(this.btnOpenLvl);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnOpenLvl]));
		w24.PackType = ((global::Gtk.PackType)(1));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnNewLevel = new global::Gtk.Button();
		this.btnNewLevel.CanFocus = true;
		this.btnNewLevel.Name = "btnNewLevel";
		this.btnNewLevel.UseUnderline = true;
		this.btnNewLevel.Relief = ((global::Gtk.ReliefStyle)(2));
		this.btnNewLevel.Label = global::Mono.Unix.Catalog.GetString("_New");
		global::Gtk.Image w25 = new global::Gtk.Image();
		w25.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-new", global::Gtk.IconSize.LargeToolbar);
		this.btnNewLevel.Image = w25;
		this.hbox3.Add(this.btnNewLevel);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnNewLevel]));
		w26.PackType = ((global::Gtk.PackType)(1));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox31 = new global::Gtk.VBox();
		this.vbox31.Name = "vbox31";
		this.vbox31.Spacing = 6;
		// Container child vbox31.Gtk.Box+BoxChild
		this.label46 = new global::Gtk.Label();
		this.label46.Name = "label46";
		this.label46.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
		this.vbox31.Add(this.label46);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.label46]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox31.Gtk.Box+BoxChild
		this.combobox3 = global::Gtk.ComboBox.NewText();
		this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("a"));
		this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("b"));
		this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("c"));
		this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("f"));
		this.combobox3.Name = "combobox3";
		this.vbox31.Add(this.combobox3);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.combobox3]));
		w29.Position = 1;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox31.Gtk.Box+BoxChild
		this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
		this.comboboxentry1.Name = "comboboxentry1";
		this.vbox31.Add(this.comboboxentry1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.comboboxentry1]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox2.Add(this.vbox31);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox31]));
		w31.Position = 3;
		w31.Expand = false;
		w31.Fill = false;
		this.notebook1.Add(this.vbox2);
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Home");
		this.notebook1.SetTabLabel(this.vbox2, this.label1);
		this.label1.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.pgtpcscript = new global::TRLevelUtility.PgTPCScript();
		this.pgtpcscript.Events = ((global::Gdk.EventMask)(256));
		this.pgtpcscript.Name = "pgtpcscript";
		this.notebook1.Add(this.pgtpcscript);
		global::Gtk.Notebook.NotebookChild w33 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.pgtpcscript]));
		w33.Position = 1;
		// Notebook tab
		this.label33 = new global::Gtk.Label();
		this.label33.Name = "label33";
		this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("Script TOMBPC");
		this.notebook1.SetTabLabel(this.pgtpcscript, this.label33);
		this.label33.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.pgtr4script = new global::TRLevelUtility.PgTR4Script();
		this.pgtr4script.Events = ((global::Gdk.EventMask)(256));
		this.pgtr4script.Name = "pgtr4script";
		this.notebook1.Add(this.pgtr4script);
		global::Gtk.Notebook.NotebookChild w34 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.pgtr4script]));
		w34.Position = 2;
		// Notebook tab
		this.label43 = new global::Gtk.Label();
		this.label43.Name = "label43";
		this.label43.LabelProp = global::Mono.Unix.Catalog.GetString("Script TR4");
		this.notebook1.SetTabLabel(this.pgtr4script, this.label43);
		this.label43.ShowAll();
		// Notebook tab
		global::Gtk.Label w35 = new global::Gtk.Label();
		w35.Visible = true;
		this.notebook1.Add(w35);
		this.label44 = new global::Gtk.Label();
		this.label44.Name = "label44";
		this.label44.LabelProp = global::Mono.Unix.Catalog.GetString("Level");
		this.notebook1.SetTabLabel(w35, this.label44);
		this.label44.ShowAll();
		this.vbox1.Add(this.notebook1);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
		w36.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.btnSave.Hide();
		this.btnSaveAs.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnSave.Clicked += new global::System.EventHandler(this.OnBtnSaveClicked);
		this.btnSaveAs.Clicked += new global::System.EventHandler(this.OnBtnSaveAsClicked);
		this.btnAbout.Clicked += new global::System.EventHandler(this.OnBtnAboutClicked);
		this.btnNewScriptTPC.Clicked += new global::System.EventHandler(this.OnBtnNewScriptTPCClicked);
		this.btnNewScriptTR4.Clicked += new global::System.EventHandler(this.OnBtnNewScriptTR4Clicked);
		this.btnOpenScript.Clicked += new global::System.EventHandler(this.OnBtnOpenScriptClicked);
		this.pgtpcscript.SaveStateChanged += new global::TRLevelUtility.SSCHdlr(this.SetSave);
		this.pgtr4script.SaveStateChanged += new global::TRLevelUtility.SSCHdlr(this.SetSave);
	}
}
