
// This file has been generated by the GUI designer. Do not modify.
namespace TRLevelUtility
{
	public partial class PgTR4Script
	{
		private global::Gtk.VBox vbox27;

		private global::Gtk.HBox hbox46;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment94;

		private global::Gtk.HBox hbox43;

		private global::Gtk.Table table3;

		private global::Gtk.Label label12;

		private global::Gtk.Label label7;

		private global::Gtk.SpinButton sbTR4InputTimeout;

		private global::TRLevelUtility.TwoBaseEntry tbeTR4Security;

		private global::Gtk.Label GtkLabel108;

		private global::Gtk.Frame frame6;

		private global::Gtk.Alignment GtkAlignment95;

		private global::Gtk.VBox vboxTR4Flags;

		private global::TRLevelUtility.TwoBaseEntry tbeTR4Flags;

		private global::Gtk.HBox hboxTR4Flags;

		private global::Gtk.CheckButton cbxTR4Flag1;

		private global::Gtk.CheckButton cbxTR4Flag2;

		private global::Gtk.CheckButton cbxTR4Flag3;

		private global::Gtk.CheckButton cbxTR4Flag4;

		private global::Gtk.CheckButton cbxTR4Flag8;

		private global::Gtk.Label GtkLabel114;

		private global::Gtk.Notebook notebook4;

		private global::Gtk.HBox hbox47;

		private global::Gtk.VBox vbox24;

		private global::TRLevelUtility.ListAddRem larTR4Levels;

		private global::TRLevelUtility.ListAddRem larTR4Filenames;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment10;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label1;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label2;

		private global::Gtk.SpinButton sbAudioTrack;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox combobox2;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.VBox vboxFlags;

		private global::TRLevelUtility.TwoBaseEntry tbeTPCFlags;

		private global::Gtk.Table table1;

		private global::Gtk.CheckButton cbxFlag1;

		private global::Gtk.CheckButton cbxFlag10;

		private global::Gtk.CheckButton cbxFlag11;

		private global::Gtk.CheckButton cbxFlag12;

		private global::Gtk.CheckButton cbxFlag13;

		private global::Gtk.CheckButton cbxFlag14;

		private global::Gtk.CheckButton cbxFlag15;

		private global::Gtk.CheckButton cbxFlag16;

		private global::Gtk.CheckButton cbxFlag2;

		private global::Gtk.CheckButton cbxFlag3;

		private global::Gtk.CheckButton cbxFlag4;

		private global::Gtk.CheckButton cbxFlag5;

		private global::Gtk.CheckButton cbxFlag6;

		private global::Gtk.CheckButton cbxFlag7;

		private global::Gtk.CheckButton cbxFlag8;

		private global::Gtk.CheckButton cbxFlag9;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label GtkLabel31;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment11;

		private global::Gtk.Label GtkLabel32;

		private global::Gtk.Label label30;

		private global::Gtk.Label label22;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TRLevelUtility.PgTR4Script
			global::Stetic.BinContainer.Attach(this);
			this.Name = "TRLevelUtility.PgTR4Script";
			// Container child TRLevelUtility.PgTR4Script.Gtk.Container+ContainerChild
			this.vbox27 = new global::Gtk.VBox();
			this.vbox27.Name = "vbox27";
			this.vbox27.Spacing = 6;
			// Container child vbox27.Gtk.Box+BoxChild
			this.hbox46 = new global::Gtk.HBox();
			this.hbox46.Name = "hbox46";
			this.hbox46.Spacing = 6;
			// Container child hbox46.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment94 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment94.Name = "GtkAlignment94";
			this.GtkAlignment94.LeftPadding = ((uint)(12));
			// Container child GtkAlignment94.Gtk.Container+ContainerChild
			this.hbox43 = new global::Gtk.HBox();
			this.hbox43.Name = "hbox43";
			this.hbox43.Spacing = 6;
			// Container child hbox43.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("XOR key (unused)");
			this.table3.Add(this.label12);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3[this.label12]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Input timeout (seconds)");
			this.table3.Add(this.label7);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.sbTR4InputTimeout = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.sbTR4InputTimeout.CanFocus = true;
			this.sbTR4InputTimeout.Name = "sbTR4InputTimeout";
			this.sbTR4InputTimeout.Adjustment.PageIncrement = 10D;
			this.sbTR4InputTimeout.ClimbRate = 1D;
			this.sbTR4InputTimeout.Numeric = true;
			this.table3.Add(this.sbTR4InputTimeout);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.sbTR4InputTimeout]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.tbeTR4Security = new global::TRLevelUtility.TwoBaseEntry();
			this.tbeTR4Security.Events = ((global::Gdk.EventMask)(256));
			this.tbeTR4Security.Name = "tbeTR4Security";
			this.tbeTR4Security.TheBase = 16;
			this.tbeTR4Security.Min = 0;
			this.tbeTR4Security.Max = 255;
			this.tbeTR4Security.Value = 0;
			this.tbeTR4Security.NumDigits = 0;
			this.table3.Add(this.tbeTR4Security);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.tbeTR4Security]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox43.Add(this.table3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox43[this.table3]));
			w5.Position = 0;
			this.GtkAlignment94.Add(this.hbox43);
			this.frame2.Add(this.GtkAlignment94);
			this.GtkLabel108 = new global::Gtk.Label();
			this.GtkLabel108.Name = "GtkLabel108";
			this.GtkLabel108.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Options</b>");
			this.GtkLabel108.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel108;
			this.hbox46.Add(this.frame2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox46[this.frame2]));
			w8.Position = 0;
			// Container child hbox46.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment95 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment95.Name = "GtkAlignment95";
			this.GtkAlignment95.LeftPadding = ((uint)(12));
			// Container child GtkAlignment95.Gtk.Container+ContainerChild
			this.vboxTR4Flags = new global::Gtk.VBox();
			this.vboxTR4Flags.Name = "vboxTR4Flags";
			this.vboxTR4Flags.Spacing = 6;
			// Container child vboxTR4Flags.Gtk.Box+BoxChild
			this.tbeTR4Flags = new global::TRLevelUtility.TwoBaseEntry();
			this.tbeTR4Flags.Events = ((global::Gdk.EventMask)(256));
			this.tbeTR4Flags.Name = "tbeTR4Flags";
			this.tbeTR4Flags.TheBase = 2;
			this.tbeTR4Flags.Min = 0;
			this.tbeTR4Flags.Max = 255;
			this.tbeTR4Flags.Value = 0;
			this.tbeTR4Flags.NumDigits = 8;
			this.vboxTR4Flags.Add(this.tbeTR4Flags);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxTR4Flags[this.tbeTR4Flags]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vboxTR4Flags.Gtk.Box+BoxChild
			this.hboxTR4Flags = new global::Gtk.HBox();
			this.hboxTR4Flags.Name = "hboxTR4Flags";
			this.hboxTR4Flags.Spacing = 6;
			// Container child hboxTR4Flags.Gtk.Box+BoxChild
			this.cbxTR4Flag1 = new global::Gtk.CheckButton();
			this.cbxTR4Flag1.CanFocus = true;
			this.cbxTR4Flag1.Name = "cbxTR4Flag1";
			this.cbxTR4Flag1.Label = global::Mono.Unix.Catalog.GetString("DOZY enabled");
			this.cbxTR4Flag1.DrawIndicator = true;
			this.cbxTR4Flag1.UseUnderline = true;
			this.hboxTR4Flags.Add(this.cbxTR4Flag1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag1]));
			w10.Position = 0;
			// Container child hboxTR4Flags.Gtk.Box+BoxChild
			this.cbxTR4Flag2 = new global::Gtk.CheckButton();
			this.cbxTR4Flag2.CanFocus = true;
			this.cbxTR4Flag2.Name = "cbxTR4Flag2";
			this.cbxTR4Flag2.Label = global::Mono.Unix.Catalog.GetString("Load/Save enabled");
			this.cbxTR4Flag2.DrawIndicator = true;
			this.cbxTR4Flag2.UseUnderline = true;
			this.hboxTR4Flags.Add(this.cbxTR4Flag2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag2]));
			w11.Position = 1;
			// Container child hboxTR4Flags.Gtk.Box+BoxChild
			this.cbxTR4Flag3 = new global::Gtk.CheckButton();
			this.cbxTR4Flag3.CanFocus = true;
			this.cbxTR4Flag3.Name = "cbxTR4Flag3";
			this.cbxTR4Flag3.Label = global::Mono.Unix.Catalog.GetString("Display title screen");
			this.cbxTR4Flag3.DrawIndicator = true;
			this.cbxTR4Flag3.UseUnderline = true;
			this.hboxTR4Flags.Add(this.cbxTR4Flag3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag3]));
			w12.Position = 2;
			// Container child hboxTR4Flags.Gtk.Box+BoxChild
			this.cbxTR4Flag4 = new global::Gtk.CheckButton();
			this.cbxTR4Flag4.CanFocus = true;
			this.cbxTR4Flag4.Name = "cbxTR4Flag4";
			this.cbxTR4Flag4.Label = global::Mono.Unix.Catalog.GetString("Select any level");
			this.cbxTR4Flag4.DrawIndicator = true;
			this.cbxTR4Flag4.UseUnderline = true;
			this.hboxTR4Flags.Add(this.cbxTR4Flag4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag4]));
			w13.Position = 3;
			// Container child hboxTR4Flags.Gtk.Box+BoxChild
			this.cbxTR4Flag8 = new global::Gtk.CheckButton();
			this.cbxTR4Flag8.CanFocus = true;
			this.cbxTR4Flag8.Name = "cbxTR4Flag8";
			this.cbxTR4Flag8.Label = global::Mono.Unix.Catalog.GetString("Demo version (no effect)");
			this.cbxTR4Flag8.DrawIndicator = true;
			this.cbxTR4Flag8.UseUnderline = true;
			this.hboxTR4Flags.Add(this.cbxTR4Flag8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxTR4Flags[this.cbxTR4Flag8]));
			w14.Position = 4;
			this.vboxTR4Flags.Add(this.hboxTR4Flags);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxTR4Flags[this.hboxTR4Flags]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.GtkAlignment95.Add(this.vboxTR4Flags);
			this.frame6.Add(this.GtkAlignment95);
			this.GtkLabel114 = new global::Gtk.Label();
			this.GtkLabel114.Name = "GtkLabel114";
			this.GtkLabel114.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Flags</b>");
			this.GtkLabel114.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel114;
			this.hbox46.Add(this.frame6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox46[this.frame6]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox27.Add(this.hbox46);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.hbox46]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.notebook4 = new global::Gtk.Notebook();
			this.notebook4.CanFocus = true;
			this.notebook4.Name = "notebook4";
			this.notebook4.CurrentPage = 0;
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.hbox47 = new global::Gtk.HBox();
			this.hbox47.Name = "hbox47";
			this.hbox47.Spacing = 6;
			// Container child hbox47.Gtk.Box+BoxChild
			this.vbox24 = new global::Gtk.VBox();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.larTR4Levels = new global::TRLevelUtility.ListAddRem();
			this.larTR4Levels.Events = ((global::Gdk.EventMask)(256));
			this.larTR4Levels.Name = "larTR4Levels";
			this.larTR4Levels.HideAddRem = false;
			this.larTR4Levels.SelectedRow = 0;
			this.larTR4Levels.MaxCount = 0;
			this.vbox24.Add(this.larTR4Levels);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.larTR4Levels]));
			w20.Position = 0;
			// Container child vbox24.Gtk.Box+BoxChild
			this.larTR4Filenames = new global::TRLevelUtility.ListAddRem();
			this.larTR4Filenames.Events = ((global::Gdk.EventMask)(256));
			this.larTR4Filenames.Name = "larTR4Filenames";
			this.larTR4Filenames.HideAddRem = false;
			this.larTR4Filenames.SelectedRow = 0;
			this.larTR4Filenames.MaxCount = 0;
			this.vbox24.Add(this.larTR4Filenames);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.larTR4Filenames]));
			w21.Position = 1;
			this.hbox47.Add(this.vbox24);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.vbox24]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox47.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment10 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment10.Name = "GtkAlignment10";
			this.GtkAlignment10.LeftPadding = ((uint)(12));
			// Container child GtkAlignment10.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("File path:");
			this.hbox6.Add(this.label1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label1]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.Name = "combobox1";
			this.hbox6.Add(this.combobox1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.combobox1]));
			w24.Position = 1;
			this.hbox5.Add(this.hbox6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox6]));
			w25.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Audio track:");
			this.hbox7.Add(this.label2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label2]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.sbAudioTrack = new global::Gtk.SpinButton(0D, 255D, 1D);
			this.sbAudioTrack.CanFocus = true;
			this.sbAudioTrack.Name = "sbAudioTrack";
			this.sbAudioTrack.Adjustment.PageIncrement = 10D;
			this.sbAudioTrack.ClimbRate = 1D;
			this.sbAudioTrack.Numeric = true;
			this.hbox7.Add(this.sbAudioTrack);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.sbAudioTrack]));
			w27.Position = 1;
			this.hbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox7]));
			w28.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Name:");
			this.hbox8.Add(this.label3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label3]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.combobox2 = global::Gtk.ComboBox.NewText();
			this.combobox2.Name = "combobox2";
			this.hbox8.Add(this.combobox2);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.combobox2]));
			w30.Position = 1;
			this.hbox5.Add(this.hbox8);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox8]));
			w31.Position = 2;
			this.vbox4.Add(this.hbox5);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vboxFlags = new global::Gtk.VBox();
			this.vboxFlags.Name = "vboxFlags";
			this.vboxFlags.Spacing = 6;
			// Container child vboxFlags.Gtk.Box+BoxChild
			this.tbeTPCFlags = new global::TRLevelUtility.TwoBaseEntry();
			this.tbeTPCFlags.Events = ((global::Gdk.EventMask)(256));
			this.tbeTPCFlags.Name = "tbeTPCFlags";
			this.tbeTPCFlags.TheBase = 2;
			this.tbeTPCFlags.Min = 0;
			this.tbeTPCFlags.Max = 65535;
			this.tbeTPCFlags.Value = 0;
			this.tbeTPCFlags.NumDigits = 16;
			this.vboxFlags.Add(this.tbeTPCFlags);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vboxFlags[this.tbeTPCFlags]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vboxFlags.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(4)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag1 = new global::Gtk.CheckButton();
			this.cbxFlag1.CanFocus = true;
			this.cbxFlag1.Name = "cbxFlag1";
			this.cbxFlag1.Label = global::Mono.Unix.Catalog.GetString("Young Lara");
			this.cbxFlag1.DrawIndicator = true;
			this.cbxFlag1.UseUnderline = true;
			this.table1.Add(this.cbxFlag1);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag1]));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag10 = new global::Gtk.CheckButton();
			this.cbxFlag10.CanFocus = true;
			this.cbxFlag10.Name = "cbxFlag10";
			this.cbxFlag10.Label = global::Mono.Unix.Catalog.GetString("ColAddHorizon");
			this.cbxFlag10.DrawIndicator = true;
			this.cbxFlag10.UseUnderline = true;
			this.table1.Add(this.cbxFlag10);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag10]));
			w35.TopAttach = ((uint)(1));
			w35.BottomAttach = ((uint)(2));
			w35.LeftAttach = ((uint)(2));
			w35.RightAttach = ((uint)(3));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag11 = new global::Gtk.CheckButton();
			this.cbxFlag11.CanFocus = true;
			this.cbxFlag11.Name = "cbxFlag11";
			this.cbxFlag11.Label = global::Mono.Unix.Catalog.GetString("ResetHUB used");
			this.cbxFlag11.DrawIndicator = true;
			this.cbxFlag11.UseUnderline = true;
			this.table1.Add(this.cbxFlag11);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag11]));
			w36.TopAttach = ((uint)(2));
			w36.BottomAttach = ((uint)(3));
			w36.LeftAttach = ((uint)(2));
			w36.RightAttach = ((uint)(3));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag12 = new global::Gtk.CheckButton();
			this.cbxFlag12.CanFocus = true;
			this.cbxFlag12.Name = "cbxFlag12";
			this.cbxFlag12.Label = global::Mono.Unix.Catalog.GetString("ColAddHorizon");
			this.cbxFlag12.DrawIndicator = true;
			this.cbxFlag12.UseUnderline = true;
			this.table1.Add(this.cbxFlag12);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag12]));
			w37.TopAttach = ((uint)(3));
			w37.BottomAttach = ((uint)(4));
			w37.LeftAttach = ((uint)(2));
			w37.RightAttach = ((uint)(3));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag13 = new global::Gtk.CheckButton();
			this.cbxFlag13.CanFocus = true;
			this.cbxFlag13.Name = "cbxFlag13";
			this.cbxFlag13.Label = global::Mono.Unix.Catalog.GetString("Timer");
			this.cbxFlag13.DrawIndicator = true;
			this.cbxFlag13.UseUnderline = true;
			this.table1.Add(this.cbxFlag13);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag13]));
			w38.LeftAttach = ((uint)(3));
			w38.RightAttach = ((uint)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag14 = new global::Gtk.CheckButton();
			this.cbxFlag14.CanFocus = true;
			this.cbxFlag14.Name = "cbxFlag14";
			this.cbxFlag14.Label = global::Mono.Unix.Catalog.GetString("Mirror used");
			this.cbxFlag14.DrawIndicator = true;
			this.cbxFlag14.UseUnderline = true;
			this.table1.Add(this.cbxFlag14);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag14]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.LeftAttach = ((uint)(3));
			w39.RightAttach = ((uint)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag15 = new global::Gtk.CheckButton();
			this.cbxFlag15.CanFocus = true;
			this.cbxFlag15.Name = "cbxFlag15";
			this.cbxFlag15.Label = global::Mono.Unix.Catalog.GetString("Remove Horus amulet");
			this.cbxFlag15.DrawIndicator = true;
			this.cbxFlag15.UseUnderline = true;
			this.table1.Add(this.cbxFlag15);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag15]));
			w40.TopAttach = ((uint)(2));
			w40.BottomAttach = ((uint)(3));
			w40.LeftAttach = ((uint)(3));
			w40.RightAttach = ((uint)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag16 = new global::Gtk.CheckButton();
			this.cbxFlag16.CanFocus = true;
			this.cbxFlag16.Name = "cbxFlag16";
			this.cbxFlag16.Label = global::Mono.Unix.Catalog.GetString("No level");
			this.cbxFlag16.DrawIndicator = true;
			this.cbxFlag16.UseUnderline = true;
			this.table1.Add(this.cbxFlag16);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag16]));
			w41.TopAttach = ((uint)(3));
			w41.BottomAttach = ((uint)(4));
			w41.LeftAttach = ((uint)(3));
			w41.RightAttach = ((uint)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag2 = new global::Gtk.CheckButton();
			this.cbxFlag2.CanFocus = true;
			this.cbxFlag2.Name = "cbxFlag2";
			this.cbxFlag2.Label = global::Mono.Unix.Catalog.GetString("Weather");
			this.cbxFlag2.DrawIndicator = true;
			this.cbxFlag2.UseUnderline = true;
			this.table1.Add(this.cbxFlag2);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag2]));
			w42.TopAttach = ((uint)(1));
			w42.BottomAttach = ((uint)(2));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag3 = new global::Gtk.CheckButton();
			this.cbxFlag3.CanFocus = true;
			this.cbxFlag3.Name = "cbxFlag3";
			this.cbxFlag3.Label = global::Mono.Unix.Catalog.GetString("Horizon");
			this.cbxFlag3.DrawIndicator = true;
			this.cbxFlag3.UseUnderline = true;
			this.table1.Add(this.cbxFlag3);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag3]));
			w43.TopAttach = ((uint)(2));
			w43.BottomAttach = ((uint)(3));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag4 = new global::Gtk.CheckButton();
			this.cbxFlag4.CanFocus = true;
			this.cbxFlag4.Name = "cbxFlag4";
			this.cbxFlag4.Label = global::Mono.Unix.Catalog.GetString("Layer2 used");
			this.cbxFlag4.DrawIndicator = true;
			this.cbxFlag4.UseUnderline = true;
			this.table1.Add(this.cbxFlag4);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag4]));
			w44.TopAttach = ((uint)(3));
			w44.BottomAttach = ((uint)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag5 = new global::Gtk.CheckButton();
			this.cbxFlag5.CanFocus = true;
			this.cbxFlag5.Name = "cbxFlag5";
			this.cbxFlag5.Label = global::Mono.Unix.Catalog.GetString("Horizon");
			this.cbxFlag5.DrawIndicator = true;
			this.cbxFlag5.UseUnderline = true;
			this.table1.Add(this.cbxFlag5);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag5]));
			w45.LeftAttach = ((uint)(1));
			w45.RightAttach = ((uint)(2));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag6 = new global::Gtk.CheckButton();
			this.cbxFlag6.CanFocus = true;
			this.cbxFlag6.Name = "cbxFlag6";
			this.cbxFlag6.Label = global::Mono.Unix.Catalog.GetString("Starfield");
			this.cbxFlag6.DrawIndicator = true;
			this.cbxFlag6.UseUnderline = true;
			this.table1.Add(this.cbxFlag6);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag6]));
			w46.TopAttach = ((uint)(1));
			w46.BottomAttach = ((uint)(2));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag7 = new global::Gtk.CheckButton();
			this.cbxFlag7.CanFocus = true;
			this.cbxFlag7.Name = "cbxFlag7";
			this.cbxFlag7.Label = global::Mono.Unix.Catalog.GetString("Lightning");
			this.cbxFlag7.DrawIndicator = true;
			this.cbxFlag7.UseUnderline = true;
			this.table1.Add(this.cbxFlag7);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag7]));
			w47.TopAttach = ((uint)(2));
			w47.BottomAttach = ((uint)(3));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag8 = new global::Gtk.CheckButton();
			this.cbxFlag8.CanFocus = true;
			this.cbxFlag8.Name = "cbxFlag8";
			this.cbxFlag8.Label = global::Mono.Unix.Catalog.GetString("Train");
			this.cbxFlag8.DrawIndicator = true;
			this.cbxFlag8.UseUnderline = true;
			this.table1.Add(this.cbxFlag8);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag8]));
			w48.TopAttach = ((uint)(3));
			w48.BottomAttach = ((uint)(4));
			w48.LeftAttach = ((uint)(1));
			w48.RightAttach = ((uint)(2));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbxFlag9 = new global::Gtk.CheckButton();
			this.cbxFlag9.CanFocus = true;
			this.cbxFlag9.Name = "cbxFlag9";
			this.cbxFlag9.Label = global::Mono.Unix.Catalog.GetString("Pulse");
			this.cbxFlag9.DrawIndicator = true;
			this.cbxFlag9.UseUnderline = true;
			this.table1.Add(this.cbxFlag9);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1[this.cbxFlag9]));
			w49.LeftAttach = ((uint)(2));
			w49.RightAttach = ((uint)(3));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxFlags.Add(this.table1);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vboxFlags[this.table1]));
			w50.Position = 1;
			w50.Expand = false;
			w50.Fill = false;
			this.notebook1.Add(this.vboxFlags);
			// Notebook tab
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Flags");
			this.notebook1.SetTabLabel(this.vboxFlags, this.label4);
			this.label4.ShowAll();
			// Notebook tab
			global::Gtk.Label w52 = new global::Gtk.Label();
			w52.Visible = true;
			this.notebook1.Add(w52);
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Level options");
			this.notebook1.SetTabLabel(w52, this.label5);
			this.label5.ShowAll();
			this.vbox4.Add(this.notebook1);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.notebook1]));
			w53.Position = 1;
			this.GtkAlignment10.Add(this.vbox4);
			this.frame1.Add(this.GtkAlignment10);
			this.GtkLabel31 = new global::Gtk.Label();
			this.GtkLabel31.Name = "GtkLabel31";
			this.GtkLabel31.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Level</b>");
			this.GtkLabel31.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel31;
			this.vbox3.Add(this.frame1);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame1]));
			w56.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment11 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment11.Name = "GtkAlignment11";
			this.GtkAlignment11.LeftPadding = ((uint)(12));
			this.frame3.Add(this.GtkAlignment11);
			this.GtkLabel32 = new global::Gtk.Label();
			this.GtkLabel32.Name = "GtkLabel32";
			this.GtkLabel32.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GtkFrame</b>");
			this.GtkLabel32.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel32;
			this.vbox3.Add(this.frame3);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame3]));
			w58.Position = 1;
			this.hbox47.Add(this.vbox3);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.vbox3]));
			w59.Position = 1;
			this.notebook4.Add(this.hbox47);
			// Notebook tab
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Levels");
			this.notebook4.SetTabLabel(this.hbox47, this.label30);
			this.label30.ShowAll();
			// Notebook tab
			global::Gtk.Label w61 = new global::Gtk.Label();
			w61.Visible = true;
			this.notebook4.Add(w61);
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Strings");
			this.notebook4.SetTabLabel(w61, this.label22);
			this.label22.ShowAll();
			this.vbox27.Add(this.notebook4);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.notebook4]));
			w62.Position = 1;
			this.Add(this.vbox27);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.tbeTR4Flags.Changed += new global::System.EventHandler(this.OnTbeTR4FlagsChanged);
			this.cbxTR4Flag1.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
			this.cbxTR4Flag2.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
			this.cbxTR4Flag3.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
			this.cbxTR4Flag4.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
			this.cbxTR4Flag8.Toggled += new global::System.EventHandler(this.tr4FlagToggle);
			this.cbxFlag9.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag8.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag7.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag6.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag5.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag4.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag3.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag2.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag16.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag15.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag14.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag13.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag12.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag11.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag10.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxFlag1.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
		}
	}
}
