
// This file has been generated by the GUI designer. Do not modify.
namespace TRLevelUtility
{
	public partial class PgTPCScript
	{
		private global::Gtk.Notebook notebook2;

		private global::TRLevelUtility.ListAddRem larTPCLevels;

		private global::Gtk.Label label8;

		private global::Gtk.HBox hbox5;

		private global::Gtk.VBox vbox22;

		private global::Gtk.Frame frame10;

		private global::Gtk.Alignment GtkAlignment88;

		private global::TRLevelUtility.ListAddRem larTPCrpl;

		private global::Gtk.Label GtkLabel115;

		private global::Gtk.Frame frame13;

		private global::Gtk.Alignment GtkAlignment96;

		private global::Gtk.Table table5;

		private global::Gtk.Label label39;

		private global::Gtk.Label label4;

		private global::Gtk.SpinButton sbTPCFMVEnd;

		private global::Gtk.SpinButton sbTPCFMVStart;

		private global::Gtk.Label GtkLabel116;

		private global::Gtk.Frame frame11;

		private global::Gtk.Alignment GtkAlignment19;

		private global::TRLevelUtility.ListAddRem larTPCcut;

		private global::Gtk.Label GtkLabel24;

		private global::Gtk.Frame frame12;

		private global::Gtk.Alignment GtkAlignment25;

		private global::TRLevelUtility.ListAddRem larTPClegal;

		private global::Gtk.Label GtkLabel30;

		private global::Gtk.Label label9;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox30;

		private global::Gtk.Frame frame5;

		private global::Gtk.Alignment GtkAlignment35;

		private global::Gtk.VBox vbox20;

		private global::Gtk.HBox hbox35;

		private global::Gtk.CheckButton cbxTPCPSX;

		private global::Gtk.CheckButton cbxTPCtr2beta;

		private global::Gtk.CheckButton cbxTPCTR3;

		private global::Gtk.Table table2;

		private global::Gtk.ComboBox cbxTPCLanguage;

		private global::Gtk.Label label25;

		private global::Gtk.Label label26;

		private global::Gtk.Label lblTPCDesc;

		private global::TRLevelUtility.TwoBaseEntry tbeTPCCypher;

		private global::Gtk.VBox vbox16;

		private global::Gtk.HBox hbox28;

		private global::Gtk.Label label24;

		private global::Gtk.ComboBox cbxTPCLoadDesc;

		private global::Gtk.ScrolledWindow GtkScrolledWindow12;

		private global::Gtk.TextView tvTPCDesc;

		private global::Gtk.Label GtkLabel54;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment36;

		private global::Gtk.VBox vbox19;

		private global::TRLevelUtility.ListAddRem larTPCdemolvls;

		private global::Gtk.SpinButton sbDemoLvl;

		private global::Gtk.Label GtkLabel55;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment38;

		private global::Gtk.Table table1;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Label label16;

		private global::Gtk.Label label17;

		private global::Gtk.Label label18;

		private global::Gtk.Label label19;

		private global::Gtk.Label label2;

		private global::Gtk.Label label20;

		private global::Gtk.Label label21;

		private global::Gtk.SpinButton sbSingleLevel;

		private global::TRLevelUtility.ScriptActionWgt tpcFirstOption;

		private global::Gtk.SpinButton tpcNoInputTime;

		private global::TRLevelUtility.ScriptActionWgt tpcOnDeathDemoMode;

		private global::TRLevelUtility.ScriptActionWgt tpcOnDeathInGame;

		private global::TRLevelUtility.ScriptActionWgt tpcOnDemoEnd;

		private global::TRLevelUtility.ScriptActionWgt tpcOnDemoInterrupt;

		private global::Gtk.SpinButton tpcSecretSound;

		private global::TRLevelUtility.ScriptActionWgt tpcTitleReplace;

		private global::Gtk.SpinButton tpcTitleSound;

		private global::Gtk.Label GtkLabel39;

		private global::Gtk.Frame frame4;

		private global::Gtk.Alignment GtkAlignment39;

		private global::Gtk.HBox hbox18;

		private global::Gtk.VBox vboxTPCFlags;

		private global::TRLevelUtility.TwoBaseEntry tbeTPCFlags;

		private global::Gtk.CheckButton cbxTPCFlag1;

		private global::Gtk.CheckButton cbxTPCFlag2;

		private global::Gtk.CheckButton cbxTPCFlag3;

		private global::Gtk.CheckButton cbxTPCFlag4;

		private global::Gtk.CheckButton cbxTPCFlag5;

		private global::Gtk.CheckButton cbxTPCFlag6;

		private global::Gtk.CheckButton cbxTPCFlag7;

		private global::Gtk.CheckButton cbxTPCFlag8;

		private global::Gtk.CheckButton cbxTPCFlag9;

		private global::Gtk.CheckButton cbxTPCFlag10;

		private global::Gtk.CheckButton cbxTPCFlag11;

		private global::Gtk.CheckButton cbxTPCFlag12;

		private global::Gtk.Label GtkLabel52;

		private global::Gtk.Label label10;

		private global::Gtk.HBox hbox32;

		private global::Gtk.Frame frame7;

		private global::Gtk.Alignment GtkAlignment43;

		private global::TRLevelUtility.ListAddRem larTPCscSlots;

		private global::Gtk.Label GtkLabel62;

		private global::Gtk.VBox vbox21;

		private global::Gtk.Frame frame8;

		private global::Gtk.Alignment GtkAlignment46;

		private global::TRLevelUtility.ListAddRem larTPCscCommands;

		private global::Gtk.Label GtkLabel66;

		private global::Gtk.Frame frame9;

		private global::Gtk.Alignment GtkAlignment52;

		private global::Gtk.Table table4;

		private global::Gtk.ComboBox cbxTPCCommand;

		private global::Gtk.Label label23;

		private global::Gtk.Label lblTPCoperandName;

		private global::Gtk.SpinButton sbTPCOperand;

		private global::Gtk.Label GtkLabel67;

		private global::Gtk.Label label11;

		private global::Gtk.Notebook notebook3;

		private global::TRLevelUtility.ListAddRem larTPCgs;

		private global::Gtk.Label label27;

		private global::TRLevelUtility.ListAddRem larTPCps;

		private global::Gtk.Label label29;

		private global::TRLevelUtility.ListAddRem larTPCpss;

		private global::Gtk.Label label3;

		private global::TRLevelUtility.ListAddRem larTPCPuzzle;

		private global::Gtk.Label label31;

		private global::TRLevelUtility.ListAddRem larTPCPickups;

		private global::Gtk.Label label36;

		private global::TRLevelUtility.ListAddRem larTPCKeys;

		private global::Gtk.Label label37;

		private global::TRLevelUtility.ListAddRem larTPCSecrets;

		private global::Gtk.Label label28;

		private global::TRLevelUtility.ListAddRem larTPCSpecial;

		private global::Gtk.Label label38;

		private global::Gtk.Label label32;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TRLevelUtility.PgTPCScript
			global::Stetic.BinContainer.Attach(this);
			this.Name = "TRLevelUtility.PgTPCScript";
			// Container child TRLevelUtility.PgTPCScript.Gtk.Container+ContainerChild
			this.notebook2 = new global::Gtk.Notebook();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 2;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.larTPCLevels = new global::TRLevelUtility.ListAddRem();
			this.larTPCLevels.Events = ((global::Gdk.EventMask)(256));
			this.larTPCLevels.Name = "larTPCLevels";
			this.larTPCLevels.HideAddRem = false;
			this.larTPCLevels.SelectedRow = 0;
			this.larTPCLevels.MaxCount = 0;
			this.notebook2.Add(this.larTPCLevels);
			// Notebook tab
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Levels");
			this.notebook2.SetTabLabel(this.larTPCLevels, this.label8);
			this.label8.ShowAll();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox22 = new global::Gtk.VBox();
			this.vbox22.Name = "vbox22";
			this.vbox22.Spacing = 6;
			// Container child vbox22.Gtk.Box+BoxChild
			this.frame10 = new global::Gtk.Frame();
			this.frame10.Name = "frame10";
			this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame10.Gtk.Container+ContainerChild
			this.GtkAlignment88 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment88.Name = "GtkAlignment88";
			this.GtkAlignment88.LeftPadding = ((uint)(12));
			// Container child GtkAlignment88.Gtk.Container+ContainerChild
			this.larTPCrpl = new global::TRLevelUtility.ListAddRem();
			this.larTPCrpl.Events = ((global::Gdk.EventMask)(256));
			this.larTPCrpl.Name = "larTPCrpl";
			this.larTPCrpl.HideAddRem = false;
			this.larTPCrpl.SelectedRow = 0;
			this.larTPCrpl.MaxCount = 0;
			this.GtkAlignment88.Add(this.larTPCrpl);
			this.frame10.Add(this.GtkAlignment88);
			this.GtkLabel115 = new global::Gtk.Label();
			this.GtkLabel115.Name = "GtkLabel115";
			this.GtkLabel115.LabelProp = global::Mono.Unix.Catalog.GetString("<b>FMV filenames</b>");
			this.GtkLabel115.UseMarkup = true;
			this.frame10.LabelWidget = this.GtkLabel115;
			this.vbox22.Add(this.frame10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.frame10]));
			w4.Position = 0;
			// Container child vbox22.Gtk.Box+BoxChild
			this.frame13 = new global::Gtk.Frame();
			this.frame13.Name = "frame13";
			this.frame13.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame13.Gtk.Container+ContainerChild
			this.GtkAlignment96 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment96.Name = "GtkAlignment96";
			this.GtkAlignment96.LeftPadding = ((uint)(12));
			// Container child GtkAlignment96.Gtk.Container+ContainerChild
			this.table5 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.label39 = new global::Gtk.Label();
			this.label39.Name = "label39";
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString("End frame");
			this.table5.Add(this.label39);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table5[this.label39]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Start frame");
			this.table5.Add(this.label4);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table5[this.label4]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.sbTPCFMVEnd = new global::Gtk.SpinButton(0D, 4294967295D, 1D);
			this.sbTPCFMVEnd.CanFocus = true;
			this.sbTPCFMVEnd.Name = "sbTPCFMVEnd";
			this.sbTPCFMVEnd.Adjustment.PageIncrement = 10D;
			this.sbTPCFMVEnd.ClimbRate = 1D;
			this.sbTPCFMVEnd.Numeric = true;
			this.table5.Add(this.sbTPCFMVEnd);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table5[this.sbTPCFMVEnd]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.sbTPCFMVStart = new global::Gtk.SpinButton(0D, 4294967295D, 1D);
			this.sbTPCFMVStart.CanFocus = true;
			this.sbTPCFMVStart.Name = "sbTPCFMVStart";
			this.sbTPCFMVStart.Adjustment.PageIncrement = 10D;
			this.sbTPCFMVStart.ClimbRate = 1D;
			this.sbTPCFMVStart.Numeric = true;
			this.table5.Add(this.sbTPCFMVStart);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table5[this.sbTPCFMVStart]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment96.Add(this.table5);
			this.frame13.Add(this.GtkAlignment96);
			this.GtkLabel116 = new global::Gtk.Label();
			this.GtkLabel116.Name = "GtkLabel116";
			this.GtkLabel116.LabelProp = global::Mono.Unix.Catalog.GetString("<b>PSX FMV info</b>");
			this.GtkLabel116.UseMarkup = true;
			this.frame13.LabelWidget = this.GtkLabel116;
			this.vbox22.Add(this.frame13);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.frame13]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox5.Add(this.vbox22);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox22]));
			w12.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.frame11 = new global::Gtk.Frame();
			this.frame11.Name = "frame11";
			this.frame11.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame11.Gtk.Container+ContainerChild
			this.GtkAlignment19 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment19.Name = "GtkAlignment19";
			this.GtkAlignment19.LeftPadding = ((uint)(12));
			// Container child GtkAlignment19.Gtk.Container+ContainerChild
			this.larTPCcut = new global::TRLevelUtility.ListAddRem();
			this.larTPCcut.Events = ((global::Gdk.EventMask)(256));
			this.larTPCcut.Name = "larTPCcut";
			this.larTPCcut.HideAddRem = false;
			this.larTPCcut.SelectedRow = 0;
			this.larTPCcut.MaxCount = 0;
			this.GtkAlignment19.Add(this.larTPCcut);
			this.frame11.Add(this.GtkAlignment19);
			this.GtkLabel24 = new global::Gtk.Label();
			this.GtkLabel24.Name = "GtkLabel24";
			this.GtkLabel24.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Cutscene filenames</b>");
			this.GtkLabel24.UseMarkup = true;
			this.frame11.LabelWidget = this.GtkLabel24;
			this.hbox5.Add(this.frame11);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame11]));
			w15.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.frame12 = new global::Gtk.Frame();
			this.frame12.Name = "frame12";
			this.frame12.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame12.Gtk.Container+ContainerChild
			this.GtkAlignment25 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment25.Name = "GtkAlignment25";
			this.GtkAlignment25.LeftPadding = ((uint)(12));
			// Container child GtkAlignment25.Gtk.Container+ContainerChild
			this.larTPClegal = new global::TRLevelUtility.ListAddRem();
			this.larTPClegal.Events = ((global::Gdk.EventMask)(256));
			this.larTPClegal.Name = "larTPClegal";
			this.larTPClegal.HideAddRem = false;
			this.larTPClegal.SelectedRow = 0;
			this.larTPClegal.MaxCount = 0;
			this.GtkAlignment25.Add(this.larTPClegal);
			this.frame12.Add(this.GtkAlignment25);
			this.GtkLabel30 = new global::Gtk.Label();
			this.GtkLabel30.Name = "GtkLabel30";
			this.GtkLabel30.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Title and pictures filenames</b>");
			this.GtkLabel30.UseMarkup = true;
			this.frame12.LabelWidget = this.GtkLabel30;
			this.hbox5.Add(this.frame12);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame12]));
			w18.Position = 2;
			this.notebook2.Add(this.hbox5);
			global::Gtk.Notebook.NotebookChild w19 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.hbox5]));
			w19.Position = 1;
			// Notebook tab
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("FMV / Cutscenes");
			this.notebook2.SetTabLabel(this.hbox5, this.label9);
			this.label9.ShowAll();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox30 = new global::Gtk.HBox();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment35 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment35.Name = "GtkAlignment35";
			this.GtkAlignment35.LeftPadding = ((uint)(12));
			// Container child GtkAlignment35.Gtk.Container+ContainerChild
			this.vbox20 = new global::Gtk.VBox();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.hbox35 = new global::Gtk.HBox();
			this.hbox35.Name = "hbox35";
			this.hbox35.Spacing = 6;
			// Container child hbox35.Gtk.Box+BoxChild
			this.cbxTPCPSX = new global::Gtk.CheckButton();
			this.cbxTPCPSX.CanFocus = true;
			this.cbxTPCPSX.Name = "cbxTPCPSX";
			this.cbxTPCPSX.Label = global::Mono.Unix.Catalog.GetString("Is PSX");
			this.cbxTPCPSX.DrawIndicator = true;
			this.cbxTPCPSX.UseUnderline = true;
			this.cbxTPCPSX.FocusOnClick = false;
			this.hbox35.Add(this.cbxTPCPSX);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.cbxTPCPSX]));
			w20.Position = 0;
			// Container child hbox35.Gtk.Box+BoxChild
			this.cbxTPCtr2beta = new global::Gtk.CheckButton();
			this.cbxTPCtr2beta.CanFocus = true;
			this.cbxTPCtr2beta.Name = "cbxTPCtr2beta";
			this.cbxTPCtr2beta.Label = global::Mono.Unix.Catalog.GetString("Is TR2 Beta");
			this.cbxTPCtr2beta.DrawIndicator = true;
			this.cbxTPCtr2beta.UseUnderline = true;
			this.hbox35.Add(this.cbxTPCtr2beta);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.cbxTPCtr2beta]));
			w21.Position = 1;
			// Container child hbox35.Gtk.Box+BoxChild
			this.cbxTPCTR3 = new global::Gtk.CheckButton();
			this.cbxTPCTR3.CanFocus = true;
			this.cbxTPCTR3.Name = "cbxTPCTR3";
			this.cbxTPCTR3.Label = global::Mono.Unix.Catalog.GetString("Is TR3");
			this.cbxTPCTR3.DrawIndicator = true;
			this.cbxTPCTR3.UseUnderline = true;
			this.hbox35.Add(this.cbxTPCTR3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.cbxTPCTR3]));
			w22.Position = 2;
			this.vbox20.Add(this.hbox35);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.hbox35]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.cbxTPCLanguage = global::Gtk.ComboBox.NewText();
			this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("English"));
			this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("French"));
			this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("German"));
			this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("American"));
			this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("Japanese"));
			this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("Italian (TR3 only)"));
			this.cbxTPCLanguage.AppendText(global::Mono.Unix.Catalog.GetString("Spanish (TR3 only)"));
			this.cbxTPCLanguage.Name = "cbxTPCLanguage";
			this.table2.Add(this.cbxTPCLanguage);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2[this.cbxTPCLanguage]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Cypher byte");
			this.table2.Add(this.label25);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2[this.label25]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label26 = new global::Gtk.Label();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Language");
			this.table2.Add(this.label26);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2[this.label26]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblTPCDesc = new global::Gtk.Label();
			this.lblTPCDesc.Name = "lblTPCDesc";
			this.lblTPCDesc.LabelProp = global::Mono.Unix.Catalog.GetString("Description\n\n256");
			this.lblTPCDesc.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add(this.lblTPCDesc);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2[this.lblTPCDesc]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.tbeTPCCypher = new global::TRLevelUtility.TwoBaseEntry();
			this.tbeTPCCypher.Events = ((global::Gdk.EventMask)(256));
			this.tbeTPCCypher.Name = "tbeTPCCypher";
			this.tbeTPCCypher.TheBase = 16;
			this.tbeTPCCypher.Min = 0;
			this.tbeTPCCypher.Max = 255;
			this.tbeTPCCypher.Value = 0;
			this.tbeTPCCypher.NumDigits = 0;
			this.table2.Add(this.tbeTPCCypher);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2[this.tbeTPCCypher]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Load existing:");
			this.hbox28.Add(this.label24);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.label24]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.cbxTPCLoadDesc = global::Gtk.ComboBox.NewText();
			this.cbxTPCLoadDesc.Name = "cbxTPCLoadDesc";
			this.hbox28.Add(this.cbxTPCLoadDesc);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.cbxTPCLoadDesc]));
			w30.Position = 1;
			this.vbox16.Add(this.hbox28);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.hbox28]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.GtkScrolledWindow12 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow12.Name = "GtkScrolledWindow12";
			this.GtkScrolledWindow12.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow12.Gtk.Container+ContainerChild
			this.tvTPCDesc = new global::Gtk.TextView();
			this.tvTPCDesc.CanFocus = true;
			this.tvTPCDesc.Name = "tvTPCDesc";
			this.GtkScrolledWindow12.Add(this.tvTPCDesc);
			this.vbox16.Add(this.GtkScrolledWindow12);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.GtkScrolledWindow12]));
			w33.Position = 1;
			this.table2.Add(this.vbox16);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox16]));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox20.Add(this.table2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.table2]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.GtkAlignment35.Add(this.vbox20);
			this.frame5.Add(this.GtkAlignment35);
			this.GtkLabel54 = new global::Gtk.Label();
			this.GtkLabel54.Name = "GtkLabel54";
			this.GtkLabel54.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Script</b>");
			this.GtkLabel54.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel54;
			this.hbox30.Add(this.frame5);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.frame5]));
			w38.Position = 0;
			// Container child hbox30.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment36 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment36.Name = "GtkAlignment36";
			this.GtkAlignment36.LeftPadding = ((uint)(12));
			// Container child GtkAlignment36.Gtk.Container+ContainerChild
			this.vbox19 = new global::Gtk.VBox();
			this.vbox19.Name = "vbox19";
			this.vbox19.Spacing = 6;
			// Container child vbox19.Gtk.Box+BoxChild
			this.larTPCdemolvls = new global::TRLevelUtility.ListAddRem();
			this.larTPCdemolvls.Events = ((global::Gdk.EventMask)(256));
			this.larTPCdemolvls.Name = "larTPCdemolvls";
			this.larTPCdemolvls.HideAddRem = false;
			this.larTPCdemolvls.SelectedRow = 0;
			this.larTPCdemolvls.MaxCount = 0;
			this.vbox19.Add(this.larTPCdemolvls);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.larTPCdemolvls]));
			w39.Position = 0;
			// Container child vbox19.Gtk.Box+BoxChild
			this.sbDemoLvl = new global::Gtk.SpinButton(0D, 65535D, 1D);
			this.sbDemoLvl.CanFocus = true;
			this.sbDemoLvl.Name = "sbDemoLvl";
			this.sbDemoLvl.Adjustment.PageIncrement = 10D;
			this.sbDemoLvl.ClimbRate = 1D;
			this.sbDemoLvl.Numeric = true;
			this.vbox19.Add(this.sbDemoLvl);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.sbDemoLvl]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			this.GtkAlignment36.Add(this.vbox19);
			this.frame1.Add(this.GtkAlignment36);
			this.GtkLabel55 = new global::Gtk.Label();
			this.GtkLabel55.Name = "GtkLabel55";
			this.GtkLabel55.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Demo levels</b>");
			this.GtkLabel55.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel55;
			this.hbox30.Add(this.frame1);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.frame1]));
			w43.Position = 1;
			this.vbox7.Add(this.hbox30);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox30]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Homogeneous = true;
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment38 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment38.Name = "GtkAlignment38";
			this.GtkAlignment38.LeftPadding = ((uint)(12));
			// Container child GtkAlignment38.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(10)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label();
			this.label13.TooltipMarkup = "What to do when the game starts";
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("First option");
			this.table1.Add(this.label13);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table1[this.label13]));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label();
			this.label14.TooltipMarkup = "What to do when ExitToTitle is requested and \"TitleDisabled\" flag is set";
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Title replace");
			this.table1.Add(this.label14);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1[this.label14]));
			w46.TopAttach = ((uint)(1));
			w46.BottomAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.TooltipMarkup = "What to do when Lara dies during the demo mode";
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("On death in demo mode");
			this.table1.Add(this.label15);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1[this.label15]));
			w47.TopAttach = ((uint)(2));
			w47.BottomAttach = ((uint)(3));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label();
			this.label16.TooltipMarkup = "What to do when Lara dies during the game";
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("On death in game");
			this.table1.Add(this.label16);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1[this.label16]));
			w48.TopAttach = ((uint)(3));
			w48.BottomAttach = ((uint)(4));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label();
			this.label17.TooltipMarkup = "Time to wait before starting a demo";
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("No input time (seconds)");
			this.table1.Add(this.label17);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1[this.label17]));
			w49.TopAttach = ((uint)(6));
			w49.BottomAttach = ((uint)(7));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label();
			this.label18.TooltipMarkup = "What to do when the demo mode is interrupted";
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("On demo interrupt");
			this.table1.Add(this.label18);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table1[this.label18]));
			w50.TopAttach = ((uint)(4));
			w50.BottomAttach = ((uint)(5));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label();
			this.label19.TooltipMarkup = "What to do when the demo mode ends";
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("On demo end");
			this.table1.Add(this.label19);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table1[this.label19]));
			w51.TopAttach = ((uint)(5));
			w51.BottomAttach = ((uint)(6));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.TooltipMarkup = "If doing only a single level, the level ID (starting at 1). -1 means disabled.";
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Single level");
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w52.TopAttach = ((uint)(9));
			w52.BottomAttach = ((uint)(10));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Title soundtrack");
			this.table1.Add(this.label20);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table1[this.label20]));
			w53.TopAttach = ((uint)(7));
			w53.BottomAttach = ((uint)(8));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("\"found a secret\" soundtrack");
			this.table1.Add(this.label21);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table1[this.label21]));
			w54.TopAttach = ((uint)(8));
			w54.BottomAttach = ((uint)(9));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.sbSingleLevel = new global::Gtk.SpinButton(-1D, 65535D, 1D);
			this.sbSingleLevel.CanFocus = true;
			this.sbSingleLevel.Name = "sbSingleLevel";
			this.sbSingleLevel.Adjustment.PageIncrement = 10D;
			this.sbSingleLevel.ClimbRate = 1D;
			this.sbSingleLevel.Numeric = true;
			this.sbSingleLevel.Value = -1D;
			this.table1.Add(this.sbSingleLevel);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table1[this.sbSingleLevel]));
			w55.TopAttach = ((uint)(9));
			w55.BottomAttach = ((uint)(10));
			w55.LeftAttach = ((uint)(1));
			w55.RightAttach = ((uint)(2));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tpcFirstOption = new global::TRLevelUtility.ScriptActionWgt();
			this.tpcFirstOption.Events = ((global::Gdk.EventMask)(256));
			this.tpcFirstOption.Name = "tpcFirstOption";
			this.tpcFirstOption.Command = 0;
			this.tpcFirstOption.UncompiledValue = ((uint)(0));
			this.tpcFirstOption.Value = ((uint)(0));
			this.table1.Add(this.tpcFirstOption);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcFirstOption]));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(2));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tpcNoInputTime = new global::Gtk.SpinButton(0D, 4294967295D, 30D);
			this.tpcNoInputTime.CanFocus = true;
			this.tpcNoInputTime.Name = "tpcNoInputTime";
			this.tpcNoInputTime.Adjustment.PageIncrement = 30D;
			this.tpcNoInputTime.ClimbRate = 1D;
			this.tpcNoInputTime.Digits = ((uint)(3));
			this.tpcNoInputTime.Numeric = true;
			this.table1.Add(this.tpcNoInputTime);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcNoInputTime]));
			w57.TopAttach = ((uint)(6));
			w57.BottomAttach = ((uint)(7));
			w57.LeftAttach = ((uint)(1));
			w57.RightAttach = ((uint)(2));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tpcOnDeathDemoMode = new global::TRLevelUtility.ScriptActionWgt();
			this.tpcOnDeathDemoMode.Events = ((global::Gdk.EventMask)(256));
			this.tpcOnDeathDemoMode.Name = "tpcOnDeathDemoMode";
			this.tpcOnDeathDemoMode.Command = 0;
			this.tpcOnDeathDemoMode.UncompiledValue = ((uint)(0));
			this.tpcOnDeathDemoMode.Value = ((uint)(0));
			this.table1.Add(this.tpcOnDeathDemoMode);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcOnDeathDemoMode]));
			w58.TopAttach = ((uint)(2));
			w58.BottomAttach = ((uint)(3));
			w58.LeftAttach = ((uint)(1));
			w58.RightAttach = ((uint)(2));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tpcOnDeathInGame = new global::TRLevelUtility.ScriptActionWgt();
			this.tpcOnDeathInGame.Events = ((global::Gdk.EventMask)(256));
			this.tpcOnDeathInGame.Name = "tpcOnDeathInGame";
			this.tpcOnDeathInGame.Command = 0;
			this.tpcOnDeathInGame.UncompiledValue = ((uint)(0));
			this.tpcOnDeathInGame.Value = ((uint)(0));
			this.table1.Add(this.tpcOnDeathInGame);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcOnDeathInGame]));
			w59.TopAttach = ((uint)(3));
			w59.BottomAttach = ((uint)(4));
			w59.LeftAttach = ((uint)(1));
			w59.RightAttach = ((uint)(2));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tpcOnDemoEnd = new global::TRLevelUtility.ScriptActionWgt();
			this.tpcOnDemoEnd.Events = ((global::Gdk.EventMask)(256));
			this.tpcOnDemoEnd.Name = "tpcOnDemoEnd";
			this.tpcOnDemoEnd.Command = 0;
			this.tpcOnDemoEnd.UncompiledValue = ((uint)(0));
			this.tpcOnDemoEnd.Value = ((uint)(0));
			this.table1.Add(this.tpcOnDemoEnd);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcOnDemoEnd]));
			w60.TopAttach = ((uint)(5));
			w60.BottomAttach = ((uint)(6));
			w60.LeftAttach = ((uint)(1));
			w60.RightAttach = ((uint)(2));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tpcOnDemoInterrupt = new global::TRLevelUtility.ScriptActionWgt();
			this.tpcOnDemoInterrupt.Events = ((global::Gdk.EventMask)(256));
			this.tpcOnDemoInterrupt.Name = "tpcOnDemoInterrupt";
			this.tpcOnDemoInterrupt.Command = 0;
			this.tpcOnDemoInterrupt.UncompiledValue = ((uint)(0));
			this.tpcOnDemoInterrupt.Value = ((uint)(0));
			this.table1.Add(this.tpcOnDemoInterrupt);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcOnDemoInterrupt]));
			w61.TopAttach = ((uint)(4));
			w61.BottomAttach = ((uint)(5));
			w61.LeftAttach = ((uint)(1));
			w61.RightAttach = ((uint)(2));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tpcSecretSound = new global::Gtk.SpinButton(0D, 65535D, 1D);
			this.tpcSecretSound.CanFocus = true;
			this.tpcSecretSound.Name = "tpcSecretSound";
			this.tpcSecretSound.Adjustment.PageIncrement = 10D;
			this.tpcSecretSound.ClimbRate = 1D;
			this.tpcSecretSound.Numeric = true;
			this.table1.Add(this.tpcSecretSound);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcSecretSound]));
			w62.TopAttach = ((uint)(8));
			w62.BottomAttach = ((uint)(9));
			w62.LeftAttach = ((uint)(1));
			w62.RightAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tpcTitleReplace = new global::TRLevelUtility.ScriptActionWgt();
			this.tpcTitleReplace.Events = ((global::Gdk.EventMask)(256));
			this.tpcTitleReplace.Name = "tpcTitleReplace";
			this.tpcTitleReplace.Command = 0;
			this.tpcTitleReplace.UncompiledValue = ((uint)(0));
			this.tpcTitleReplace.Value = ((uint)(0));
			this.table1.Add(this.tpcTitleReplace);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcTitleReplace]));
			w63.TopAttach = ((uint)(1));
			w63.BottomAttach = ((uint)(2));
			w63.LeftAttach = ((uint)(1));
			w63.RightAttach = ((uint)(2));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tpcTitleSound = new global::Gtk.SpinButton(0D, 65535D, 1D);
			this.tpcTitleSound.CanFocus = true;
			this.tpcTitleSound.Name = "tpcTitleSound";
			this.tpcTitleSound.Adjustment.PageIncrement = 10D;
			this.tpcTitleSound.ClimbRate = 1D;
			this.tpcTitleSound.Numeric = true;
			this.table1.Add(this.tpcTitleSound);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table1[this.tpcTitleSound]));
			w64.TopAttach = ((uint)(7));
			w64.BottomAttach = ((uint)(8));
			w64.LeftAttach = ((uint)(1));
			w64.RightAttach = ((uint)(2));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment38.Add(this.table1);
			this.frame3.Add(this.GtkAlignment38);
			this.GtkLabel39 = new global::Gtk.Label();
			this.GtkLabel39.Name = "GtkLabel39";
			this.GtkLabel39.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Options</b>");
			this.GtkLabel39.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel39;
			this.hbox11.Add(this.frame3);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.frame3]));
			w67.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment39 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment39.Name = "GtkAlignment39";
			this.GtkAlignment39.LeftPadding = ((uint)(12));
			// Container child GtkAlignment39.Gtk.Container+ContainerChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.vboxTPCFlags = new global::Gtk.VBox();
			this.vboxTPCFlags.Name = "vboxTPCFlags";
			this.vboxTPCFlags.Spacing = 6;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.tbeTPCFlags = new global::TRLevelUtility.TwoBaseEntry();
			this.tbeTPCFlags.Events = ((global::Gdk.EventMask)(256));
			this.tbeTPCFlags.Name = "tbeTPCFlags";
			this.tbeTPCFlags.TheBase = 2;
			this.tbeTPCFlags.Min = 0;
			this.tbeTPCFlags.Max = 65535;
			this.tbeTPCFlags.Value = 0;
			this.tbeTPCFlags.NumDigits = 16;
			this.vboxTPCFlags.Add(this.tbeTPCFlags);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.tbeTPCFlags]));
			w68.Position = 0;
			w68.Expand = false;
			w68.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag1 = new global::Gtk.CheckButton();
			this.cbxTPCFlag1.CanFocus = true;
			this.cbxTPCFlag1.Name = "cbxTPCFlag1";
			this.cbxTPCFlag1.Label = global::Mono.Unix.Catalog.GetString("Demo version");
			this.cbxTPCFlag1.DrawIndicator = true;
			this.cbxTPCFlag1.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag1);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag1]));
			w69.Position = 1;
			w69.Expand = false;
			w69.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag2 = new global::Gtk.CheckButton();
			this.cbxTPCFlag2.CanFocus = true;
			this.cbxTPCFlag2.Name = "cbxTPCFlag2";
			this.cbxTPCFlag2.Label = global::Mono.Unix.Catalog.GetString("Title disabled");
			this.cbxTPCFlag2.DrawIndicator = true;
			this.cbxTPCFlag2.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag2);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag2]));
			w70.Position = 2;
			w70.Expand = false;
			w70.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag3 = new global::Gtk.CheckButton();
			this.cbxTPCFlag3.CanFocus = true;
			this.cbxTPCFlag3.Name = "cbxTPCFlag3";
			this.cbxTPCFlag3.Label = global::Mono.Unix.Catalog.GetString("Cheat sequence disabled (all weapons & invincibility)");
			this.cbxTPCFlag3.DrawIndicator = true;
			this.cbxTPCFlag3.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag3);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag3]));
			w71.Position = 3;
			w71.Expand = false;
			w71.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag4 = new global::Gtk.CheckButton();
			this.cbxTPCFlag4.CanFocus = true;
			this.cbxTPCFlag4.Name = "cbxTPCFlag4";
			this.cbxTPCFlag4.Label = global::Mono.Unix.Catalog.GetString("No input timeout (the game doesn\'t enter demo mode after a specified delay)");
			this.cbxTPCFlag4.DrawIndicator = true;
			this.cbxTPCFlag4.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag4);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag4]));
			w72.Position = 4;
			w72.Expand = false;
			w72.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag5 = new global::Gtk.CheckButton();
			this.cbxTPCFlag5.CanFocus = true;
			this.cbxTPCFlag5.Name = "cbxTPCFlag5";
			this.cbxTPCFlag5.Label = global::Mono.Unix.Catalog.GetString("Load/Save disabled");
			this.cbxTPCFlag5.DrawIndicator = true;
			this.cbxTPCFlag5.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag5);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag5]));
			w73.Position = 5;
			w73.Expand = false;
			w73.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag6 = new global::Gtk.CheckButton();
			this.cbxTPCFlag6.CanFocus = true;
			this.cbxTPCFlag6.Name = "cbxTPCFlag6";
			this.cbxTPCFlag6.Label = global::Mono.Unix.Catalog.GetString("Screen sizing keys disabled (F1-F4)");
			this.cbxTPCFlag6.DrawIndicator = true;
			this.cbxTPCFlag6.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag6);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag6]));
			w74.Position = 6;
			w74.Expand = false;
			w74.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag7 = new global::Gtk.CheckButton();
			this.cbxTPCFlag7.CanFocus = true;
			this.cbxTPCFlag7.Name = "cbxTPCFlag7";
			this.cbxTPCFlag7.Label = global::Mono.Unix.Catalog.GetString("Lock out option ring");
			this.cbxTPCFlag7.DrawIndicator = true;
			this.cbxTPCFlag7.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag7);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag7]));
			w75.Position = 7;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag8 = new global::Gtk.CheckButton();
			this.cbxTPCFlag8.CanFocus = true;
			this.cbxTPCFlag8.Name = "cbxTPCFlag8";
			this.cbxTPCFlag8.Label = global::Mono.Unix.Catalog.GetString("DOZY cheat enabled (no effect in-game)");
			this.cbxTPCFlag8.DrawIndicator = true;
			this.cbxTPCFlag8.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag8);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag8]));
			w76.Position = 8;
			w76.Expand = false;
			w76.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag9 = new global::Gtk.CheckButton();
			this.cbxTPCFlag9.CanFocus = true;
			this.cbxTPCFlag9.Name = "cbxTPCFlag9";
			this.cbxTPCFlag9.Label = global::Mono.Unix.Catalog.GetString("Use security tag (encrypt strings using the specified XOR key)");
			this.cbxTPCFlag9.DrawIndicator = true;
			this.cbxTPCFlag9.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag9);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag9]));
			w77.Position = 9;
			w77.Expand = false;
			w77.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag10 = new global::Gtk.CheckButton();
			this.cbxTPCFlag10.CanFocus = true;
			this.cbxTPCFlag10.Name = "cbxTPCFlag10";
			this.cbxTPCFlag10.Label = global::Mono.Unix.Catalog.GetString("Enable gym (usually set, no effect if disabled)");
			this.cbxTPCFlag10.DrawIndicator = true;
			this.cbxTPCFlag10.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag10);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag10]));
			w78.Position = 10;
			w78.Expand = false;
			w78.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag11 = new global::Gtk.CheckButton();
			this.cbxTPCFlag11.CanFocus = true;
			this.cbxTPCFlag11.Name = "cbxTPCFlag11";
			this.cbxTPCFlag11.Label = global::Mono.Unix.Catalog.GetString("Select any level (all levels are listed when choosing \'New Game\')");
			this.cbxTPCFlag11.DrawIndicator = true;
			this.cbxTPCFlag11.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag11);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag11]));
			w79.Position = 11;
			w79.Expand = false;
			w79.Fill = false;
			// Container child vboxTPCFlags.Gtk.Box+BoxChild
			this.cbxTPCFlag12 = new global::Gtk.CheckButton();
			this.cbxTPCFlag12.CanFocus = true;
			this.cbxTPCFlag12.Name = "cbxTPCFlag12";
			this.cbxTPCFlag12.Label = global::Mono.Unix.Catalog.GetString("Enable cheat code (no apparent effect)");
			this.cbxTPCFlag12.DrawIndicator = true;
			this.cbxTPCFlag12.UseUnderline = true;
			this.vboxTPCFlags.Add(this.cbxTPCFlag12);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vboxTPCFlags[this.cbxTPCFlag12]));
			w80.Position = 12;
			w80.Expand = false;
			w80.Fill = false;
			this.hbox18.Add(this.vboxTPCFlags);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.vboxTPCFlags]));
			w81.Position = 0;
			this.GtkAlignment39.Add(this.hbox18);
			this.frame4.Add(this.GtkAlignment39);
			this.GtkLabel52 = new global::Gtk.Label();
			this.GtkLabel52.Name = "GtkLabel52";
			this.GtkLabel52.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Flags</b>");
			this.GtkLabel52.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel52;
			this.hbox11.Add(this.frame4);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.frame4]));
			w84.Position = 1;
			this.vbox7.Add(this.hbox11);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox11]));
			w85.Position = 1;
			this.notebook2.Add(this.vbox7);
			global::Gtk.Notebook.NotebookChild w86 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.vbox7]));
			w86.Position = 2;
			// Notebook tab
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Options");
			this.notebook2.SetTabLabel(this.vbox7, this.label10);
			this.label10.ShowAll();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.hbox32 = new global::Gtk.HBox();
			this.hbox32.Name = "hbox32";
			this.hbox32.Spacing = 6;
			// Container child hbox32.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment43 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment43.Name = "GtkAlignment43";
			this.GtkAlignment43.LeftPadding = ((uint)(12));
			// Container child GtkAlignment43.Gtk.Container+ContainerChild
			this.larTPCscSlots = new global::TRLevelUtility.ListAddRem();
			this.larTPCscSlots.Events = ((global::Gdk.EventMask)(256));
			this.larTPCscSlots.Name = "larTPCscSlots";
			this.larTPCscSlots.HideAddRem = false;
			this.larTPCscSlots.SelectedRow = 0;
			this.larTPCscSlots.MaxCount = 0;
			this.GtkAlignment43.Add(this.larTPCscSlots);
			this.frame7.Add(this.GtkAlignment43);
			this.GtkLabel62 = new global::Gtk.Label();
			this.GtkLabel62.Name = "GtkLabel62";
			this.GtkLabel62.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Script slots</b>");
			this.GtkLabel62.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel62;
			this.hbox32.Add(this.frame7);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.frame7]));
			w89.Position = 0;
			w89.Expand = false;
			w89.Fill = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.vbox21 = new global::Gtk.VBox();
			this.vbox21.Name = "vbox21";
			this.vbox21.Spacing = 6;
			// Container child vbox21.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment46 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment46.Name = "GtkAlignment46";
			this.GtkAlignment46.LeftPadding = ((uint)(12));
			// Container child GtkAlignment46.Gtk.Container+ContainerChild
			this.larTPCscCommands = new global::TRLevelUtility.ListAddRem();
			this.larTPCscCommands.Events = ((global::Gdk.EventMask)(256));
			this.larTPCscCommands.Name = "larTPCscCommands";
			this.larTPCscCommands.HideAddRem = false;
			this.larTPCscCommands.SelectedRow = 0;
			this.larTPCscCommands.MaxCount = 0;
			this.GtkAlignment46.Add(this.larTPCscCommands);
			this.frame8.Add(this.GtkAlignment46);
			this.GtkLabel66 = new global::Gtk.Label();
			this.GtkLabel66.Name = "GtkLabel66";
			this.GtkLabel66.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Script commands</b>");
			this.GtkLabel66.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel66;
			this.vbox21.Add(this.frame8);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.frame8]));
			w92.Position = 0;
			// Container child vbox21.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment52 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment52.Name = "GtkAlignment52";
			this.GtkAlignment52.LeftPadding = ((uint)(12));
			// Container child GtkAlignment52.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.cbxTPCCommand = global::Gtk.ComboBox.NewText();
			this.cbxTPCCommand.Sensitive = false;
			this.cbxTPCCommand.Name = "cbxTPCCommand";
			this.table4.Add(this.cbxTPCCommand);
			global::Gtk.Table.TableChild w93 = ((global::Gtk.Table.TableChild)(this.table4[this.cbxTPCCommand]));
			w93.LeftAttach = ((uint)(1));
			w93.RightAttach = ((uint)(2));
			w93.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Command");
			this.table4.Add(this.label23);
			global::Gtk.Table.TableChild w94 = ((global::Gtk.Table.TableChild)(this.table4[this.label23]));
			w94.XOptions = ((global::Gtk.AttachOptions)(4));
			w94.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lblTPCoperandName = new global::Gtk.Label();
			this.lblTPCoperandName.Name = "lblTPCoperandName";
			this.lblTPCoperandName.LabelProp = global::Mono.Unix.Catalog.GetString("Operand");
			this.table4.Add(this.lblTPCoperandName);
			global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.table4[this.lblTPCoperandName]));
			w95.TopAttach = ((uint)(1));
			w95.BottomAttach = ((uint)(2));
			w95.XOptions = ((global::Gtk.AttachOptions)(4));
			w95.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.sbTPCOperand = new global::Gtk.SpinButton(0D, 65535D, 1D);
			this.sbTPCOperand.Sensitive = false;
			this.sbTPCOperand.CanFocus = true;
			this.sbTPCOperand.Name = "sbTPCOperand";
			this.sbTPCOperand.Adjustment.PageIncrement = 10D;
			this.sbTPCOperand.ClimbRate = 1D;
			this.sbTPCOperand.Numeric = true;
			this.table4.Add(this.sbTPCOperand);
			global::Gtk.Table.TableChild w96 = ((global::Gtk.Table.TableChild)(this.table4[this.sbTPCOperand]));
			w96.TopAttach = ((uint)(1));
			w96.BottomAttach = ((uint)(2));
			w96.LeftAttach = ((uint)(1));
			w96.RightAttach = ((uint)(2));
			w96.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment52.Add(this.table4);
			this.frame9.Add(this.GtkAlignment52);
			this.GtkLabel67 = new global::Gtk.Label();
			this.GtkLabel67.Name = "GtkLabel67";
			this.GtkLabel67.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Command options</b>");
			this.GtkLabel67.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel67;
			this.vbox21.Add(this.frame9);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.frame9]));
			w99.Position = 1;
			w99.Expand = false;
			w99.Fill = false;
			this.hbox32.Add(this.vbox21);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.vbox21]));
			w100.Position = 1;
			this.notebook2.Add(this.hbox32);
			global::Gtk.Notebook.NotebookChild w101 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.hbox32]));
			w101.Position = 3;
			// Notebook tab
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Script");
			this.notebook2.SetTabLabel(this.hbox32, this.label11);
			this.label11.ShowAll();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.notebook3 = new global::Gtk.Notebook();
			this.notebook3.CanFocus = true;
			this.notebook3.Name = "notebook3";
			this.notebook3.CurrentPage = 2;
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.larTPCgs = new global::TRLevelUtility.ListAddRem();
			this.larTPCgs.Events = ((global::Gdk.EventMask)(256));
			this.larTPCgs.Name = "larTPCgs";
			this.larTPCgs.HideAddRem = false;
			this.larTPCgs.SelectedRow = 0;
			this.larTPCgs.MaxCount = 0;
			this.notebook3.Add(this.larTPCgs);
			// Notebook tab
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Game strings");
			this.notebook3.SetTabLabel(this.larTPCgs, this.label27);
			this.label27.ShowAll();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.larTPCps = new global::TRLevelUtility.ListAddRem();
			this.larTPCps.Events = ((global::Gdk.EventMask)(256));
			this.larTPCps.Name = "larTPCps";
			this.larTPCps.HideAddRem = false;
			this.larTPCps.SelectedRow = 0;
			this.larTPCps.MaxCount = 0;
			this.notebook3.Add(this.larTPCps);
			global::Gtk.Notebook.NotebookChild w103 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCps]));
			w103.Position = 1;
			// Notebook tab
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("PC strings");
			this.notebook3.SetTabLabel(this.larTPCps, this.label29);
			this.label29.ShowAll();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.larTPCpss = new global::TRLevelUtility.ListAddRem();
			this.larTPCpss.Events = ((global::Gdk.EventMask)(256));
			this.larTPCpss.Name = "larTPCpss";
			this.larTPCpss.HideAddRem = false;
			this.larTPCpss.SelectedRow = 0;
			this.larTPCpss.MaxCount = 0;
			this.notebook3.Add(this.larTPCpss);
			global::Gtk.Notebook.NotebookChild w104 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCpss]));
			w104.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("PSX strings");
			this.notebook3.SetTabLabel(this.larTPCpss, this.label3);
			this.label3.ShowAll();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.larTPCPuzzle = new global::TRLevelUtility.ListAddRem();
			this.larTPCPuzzle.Events = ((global::Gdk.EventMask)(256));
			this.larTPCPuzzle.Name = "larTPCPuzzle";
			this.larTPCPuzzle.HideAddRem = false;
			this.larTPCPuzzle.SelectedRow = 0;
			this.larTPCPuzzle.MaxCount = 0;
			this.notebook3.Add(this.larTPCPuzzle);
			global::Gtk.Notebook.NotebookChild w105 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCPuzzle]));
			w105.Position = 3;
			// Notebook tab
			this.label31 = new global::Gtk.Label();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Puzzle");
			this.notebook3.SetTabLabel(this.larTPCPuzzle, this.label31);
			this.label31.ShowAll();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.larTPCPickups = new global::TRLevelUtility.ListAddRem();
			this.larTPCPickups.Events = ((global::Gdk.EventMask)(256));
			this.larTPCPickups.Name = "larTPCPickups";
			this.larTPCPickups.HideAddRem = false;
			this.larTPCPickups.SelectedRow = 0;
			this.larTPCPickups.MaxCount = 0;
			this.notebook3.Add(this.larTPCPickups);
			global::Gtk.Notebook.NotebookChild w106 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCPickups]));
			w106.Position = 4;
			// Notebook tab
			this.label36 = new global::Gtk.Label();
			this.label36.Name = "label36";
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString("Pickups");
			this.notebook3.SetTabLabel(this.larTPCPickups, this.label36);
			this.label36.ShowAll();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.larTPCKeys = new global::TRLevelUtility.ListAddRem();
			this.larTPCKeys.Events = ((global::Gdk.EventMask)(256));
			this.larTPCKeys.Name = "larTPCKeys";
			this.larTPCKeys.HideAddRem = true;
			this.larTPCKeys.SelectedRow = 0;
			this.larTPCKeys.MaxCount = 0;
			this.notebook3.Add(this.larTPCKeys);
			global::Gtk.Notebook.NotebookChild w107 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCKeys]));
			w107.Position = 5;
			// Notebook tab
			this.label37 = new global::Gtk.Label();
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString("Keys");
			this.notebook3.SetTabLabel(this.larTPCKeys, this.label37);
			this.label37.ShowAll();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.larTPCSecrets = new global::TRLevelUtility.ListAddRem();
			this.larTPCSecrets.Events = ((global::Gdk.EventMask)(256));
			this.larTPCSecrets.Name = "larTPCSecrets";
			this.larTPCSecrets.HideAddRem = false;
			this.larTPCSecrets.SelectedRow = 0;
			this.larTPCSecrets.MaxCount = 0;
			this.notebook3.Add(this.larTPCSecrets);
			global::Gtk.Notebook.NotebookChild w108 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCSecrets]));
			w108.Position = 6;
			// Notebook tab
			this.label28 = new global::Gtk.Label();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("Secrets");
			this.notebook3.SetTabLabel(this.larTPCSecrets, this.label28);
			this.label28.ShowAll();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.larTPCSpecial = new global::TRLevelUtility.ListAddRem();
			this.larTPCSpecial.Events = ((global::Gdk.EventMask)(256));
			this.larTPCSpecial.Name = "larTPCSpecial";
			this.larTPCSpecial.HideAddRem = false;
			this.larTPCSpecial.SelectedRow = 0;
			this.larTPCSpecial.MaxCount = 0;
			this.notebook3.Add(this.larTPCSpecial);
			global::Gtk.Notebook.NotebookChild w109 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.larTPCSpecial]));
			w109.Position = 7;
			// Notebook tab
			this.label38 = new global::Gtk.Label();
			this.label38.Name = "label38";
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString("Special");
			this.notebook3.SetTabLabel(this.larTPCSpecial, this.label38);
			this.label38.ShowAll();
			this.notebook2.Add(this.notebook3);
			global::Gtk.Notebook.NotebookChild w110 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.notebook3]));
			w110.Position = 4;
			// Notebook tab
			this.label32 = new global::Gtk.Label();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("Strings");
			this.notebook2.SetTabLabel(this.notebook3, this.label32);
			this.label32.ShowAll();
			this.Add(this.notebook2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.notebook2.SwitchPage += new global::Gtk.SwitchPageHandler(this.OnNotebook2SwitchPage);
			this.larTPCLevels.RowAdded += new global::TRLevelUtility.ListAddRem.RowAddedHdlr(this.OnLarTPCLevelsRowAdded);
			this.larTPCLevels.RowRemoved += new global::TRLevelUtility.ListAddRem.RowRemovedHdlr(this.OnLarTPCLevelsRowRemoved);
			this.larTPCLevels.RowEdited += new global::TRLevelUtility.ListAddRem.RowEditedHdlr(this.OnLarTPCLevelsRowEdited);
			this.larTPCLevels.RowMoved += new global::TRLevelUtility.ListAddRem.RowMovedHdlr(this.OnLarTPCLevelsRowMoved);
			this.larTPCrpl.RowAdded += new global::TRLevelUtility.ListAddRem.RowAddedHdlr(this.OnLarTPCrplRowAdded);
			this.larTPCrpl.RowRemoved += new global::TRLevelUtility.ListAddRem.RowRemovedHdlr(this.OnLarTPCrplRowRemoved);
			this.larTPCrpl.RowMoved += new global::TRLevelUtility.ListAddRem.RowMovedHdlr(this.OnLarTPCrplRowMoved);
			this.larTPCrpl.SelectionChanged += new global::TRLevelUtility.ListAddRem.EmptyHdlr(this.OnLarTPCrplSelectionChanged);
			this.sbTPCFMVStart.ValueChanged += new global::System.EventHandler(this.OnSbTPCFMVStartValueChanged);
			this.sbTPCFMVEnd.ValueChanged += new global::System.EventHandler(this.OnSbTPCFMVEndValueChanged);
			this.cbxTPCPSX.Toggled += new global::System.EventHandler(this.OnCbxTPCPSXToggled);
			this.cbxTPCtr2beta.Toggled += new global::System.EventHandler(this.OnCbxTPCtr2betaToggled);
			this.cbxTPCTR3.Toggled += new global::System.EventHandler(this.OnCbxTPCTR3Toggled);
			this.cbxTPCLoadDesc.Changed += new global::System.EventHandler(this.OnCbxTPCLoadDescChanged);
			this.larTPCdemolvls.RowAdded += new global::TRLevelUtility.ListAddRem.RowAddedHdlr(this.OnLarTPCdemolvlsRowAdded);
			this.larTPCdemolvls.RowRemoved += new global::TRLevelUtility.ListAddRem.RowRemovedHdlr(this.OnLarTPCdemolvlsRowRemoved);
			this.larTPCdemolvls.RowEdited += new global::TRLevelUtility.ListAddRem.RowEditedHdlr(this.OnLarTPCdemolvlsRowEdited);
			this.larTPCdemolvls.SelectionChanged += new global::TRLevelUtility.ListAddRem.EmptyHdlr(this.OnLarTPCdemolvlsSelectionChanged);
			this.larTPCdemolvls.RowMoved += new global::TRLevelUtility.ListAddRem.RowMovedHdlr(this.OnLarTPCdemolvlsRowMoved);
			this.sbDemoLvl.ValueChanged += new global::System.EventHandler(this.OnSbDemoLvlValueChanged);
			this.tpcNoInputTime.Input += new global::Gtk.InputHandler(this.OnTpcNoInputTimeInput);
			this.tpcNoInputTime.Output += new global::Gtk.OutputHandler(this.OnTpcNoInputTimeOutput);
			this.tbeTPCFlags.Changed += new global::System.EventHandler(this.OnTbeTPCFlagsChanged);
			this.cbxTPCFlag1.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag2.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag3.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag4.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag5.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag6.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag7.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag8.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag9.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag10.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag11.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.cbxTPCFlag12.Toggled += new global::System.EventHandler(this.tpcFlagToggle);
			this.larTPCscSlots.SelectionChanged += new global::TRLevelUtility.ListAddRem.EmptyHdlr(this.OnLarTPCscSlotsSelectionChanged);
			this.larTPCscCommands.RowAdded += new global::TRLevelUtility.ListAddRem.RowAddedHdlr(this.OnLarTPCscCommandsRowAdded);
			this.larTPCscCommands.RowRemoved += new global::TRLevelUtility.ListAddRem.RowRemovedHdlr(this.OnLarTPCscCommandsRowRemoved);
			this.larTPCscCommands.RowMoved += new global::TRLevelUtility.ListAddRem.RowMovedHdlr(this.OnLarTPCscCommandsRowMoved);
			this.larTPCscCommands.SelectionChanged += new global::TRLevelUtility.ListAddRem.EmptyHdlr(this.OnLarTPCscCommandsSelectionChanged);
			this.sbTPCOperand.Output += new global::Gtk.OutputHandler(this.OnSbTPCOperandOutput);
			this.sbTPCOperand.ValueChanged += new global::System.EventHandler(this.OnSbTPCOperandValueChanged);
			this.cbxTPCCommand.Changed += new global::System.EventHandler(this.OnCbxTPCCommandChanged);
		}
	}
}
