
// This file has been generated by the GUI designer. Do not modify.
namespace TRLevelUtility
{
	public partial class ListAddRem
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvMain;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button btnAdd;

		private global::Gtk.Button btnMoveUp;

		private global::Gtk.Button btnDuplicate;

		private global::Gtk.Button btnMoveDown;

		private global::Gtk.Button btnRemove;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TRLevelUtility.ListAddRem
			global::Stetic.BinContainer.Attach(this);
			this.Name = "TRLevelUtility.ListAddRem";
			// Container child TRLevelUtility.ListAddRem.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvMain = new global::Gtk.TreeView();
			this.tvMain.CanFocus = true;
			this.tvMain.Name = "tvMain";
			this.tvMain.EnableSearch = false;
			this.tvMain.RulesHint = true;
			this.GtkScrolledWindow.Add(this.tvMain);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnAdd = new global::Gtk.Button();
			this.btnAdd.CanFocus = true;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.UseUnderline = true;
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.LargeToolbar);
			this.btnAdd.Image = w3;
			this.hbox2.Add(this.btnAdd);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnAdd]));
			w4.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnMoveUp = new global::Gtk.Button();
			this.btnMoveUp.CanFocus = true;
			this.btnMoveUp.Name = "btnMoveUp";
			this.btnMoveUp.UseUnderline = true;
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-go-up", global::Gtk.IconSize.LargeToolbar);
			this.btnMoveUp.Image = w5;
			this.hbox2.Add(this.btnMoveUp);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnMoveUp]));
			w6.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnDuplicate = new global::Gtk.Button();
			this.btnDuplicate.CanFocus = true;
			this.btnDuplicate.Name = "btnDuplicate";
			this.btnDuplicate.UseUnderline = true;
			global::Gtk.Image w7 = new global::Gtk.Image();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-copy", global::Gtk.IconSize.LargeToolbar);
			this.btnDuplicate.Image = w7;
			this.hbox2.Add(this.btnDuplicate);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnDuplicate]));
			w8.Position = 2;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnMoveDown = new global::Gtk.Button();
			this.btnMoveDown.CanFocus = true;
			this.btnMoveDown.Name = "btnMoveDown";
			this.btnMoveDown.UseUnderline = true;
			global::Gtk.Image w9 = new global::Gtk.Image();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-go-down", global::Gtk.IconSize.LargeToolbar);
			this.btnMoveDown.Image = w9;
			this.hbox2.Add(this.btnMoveDown);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnMoveDown]));
			w10.Position = 3;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnRemove = new global::Gtk.Button();
			this.btnRemove.CanFocus = true;
			this.btnRemove.Name = "btnRemove";
			this.btnRemove.UseUnderline = true;
			global::Gtk.Image w11 = new global::Gtk.Image();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-remove", global::Gtk.IconSize.LargeToolbar);
			this.btnRemove.Image = w11;
			this.hbox2.Add(this.btnRemove);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnRemove]));
			w12.Position = 4;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btnAdd.Clicked += new global::System.EventHandler(this.OnBtnAddClicked);
			this.btnMoveUp.Clicked += new global::System.EventHandler(this.OnBtnMoveUpClicked);
			this.btnDuplicate.Clicked += new global::System.EventHandler(this.OnBtnDuplicateClicked);
			this.btnMoveDown.Clicked += new global::System.EventHandler(this.OnBtnMoveDownClicked);
			this.btnRemove.Clicked += new global::System.EventHandler(this.OnBtnRemoveClicked);
		}
	}
}
