
// This file has been generated by the GUI designer. Do not modify.
namespace TRLevelUtility
{
	public partial class PgRAW
	{
		private global::Gtk.Notebook notebook1;

		private global::TRLevelUtility.HexViewWgt hexviewwgt1;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label6;

		private global::Gtk.Entry txtIMGOffset;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtIMGWidth;

		private global::Gtk.Label label4;

		private global::Gtk.Entry txtIMGHeight;

		private global::Gtk.Label label5;

		private global::Gtk.ComboBox cbxPixelFormat;

		private global::Gtk.CheckButton cbxBGR;

		private global::Gtk.Button btnLoadImg;

		private global::Gtk.Button btnSaveIMG;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.Image imgRAW;

		private global::Gtk.Label label2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TRLevelUtility.PgRAW
			global::Stetic.BinContainer.Attach(this);
			this.Name = "TRLevelUtility.PgRAW";
			// Container child TRLevelUtility.PgRAW.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hexviewwgt1 = new global::TRLevelUtility.HexViewWgt();
			this.hexviewwgt1.Events = ((global::Gdk.EventMask)(256));
			this.hexviewwgt1.Name = "hexviewwgt1";
			this.notebook1.Add(this.hexviewwgt1);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Hexadecimal view");
			this.notebook1.SetTabLabel(this.hexviewwgt1, this.label1);
			this.label1.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.hbox3.BorderWidth = ((uint)(6));
			// Container child hbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Data offset :");
			this.hbox3.Add(this.label6);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label6]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtIMGOffset = new global::Gtk.Entry();
			this.txtIMGOffset.CanFocus = true;
			this.txtIMGOffset.Name = "txtIMGOffset";
			this.txtIMGOffset.IsEditable = true;
			this.txtIMGOffset.InvisibleChar = '●';
			this.hbox3.Add(this.txtIMGOffset);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtIMGOffset]));
			w3.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Width :");
			this.hbox3.Add(this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label3]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtIMGWidth = new global::Gtk.Entry();
			this.txtIMGWidth.CanFocus = true;
			this.txtIMGWidth.Name = "txtIMGWidth";
			this.txtIMGWidth.IsEditable = true;
			this.txtIMGWidth.InvisibleChar = '●';
			this.hbox3.Add(this.txtIMGWidth);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtIMGWidth]));
			w5.Position = 3;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Height :");
			this.hbox3.Add(this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label4]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtIMGHeight = new global::Gtk.Entry();
			this.txtIMGHeight.CanFocus = true;
			this.txtIMGHeight.Name = "txtIMGHeight";
			this.txtIMGHeight.IsEditable = true;
			this.txtIMGHeight.InvisibleChar = '●';
			this.hbox3.Add(this.txtIMGHeight);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtIMGHeight]));
			w7.Position = 5;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Format :");
			this.hbox3.Add(this.label5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label5]));
			w8.Position = 6;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.cbxPixelFormat = global::Gtk.ComboBox.NewText();
			this.cbxPixelFormat.Name = "cbxPixelFormat";
			this.hbox3.Add(this.cbxPixelFormat);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.cbxPixelFormat]));
			w9.Position = 7;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.cbxBGR = new global::Gtk.CheckButton();
			this.cbxBGR.CanFocus = true;
			this.cbxBGR.Name = "cbxBGR";
			this.cbxBGR.Label = global::Mono.Unix.Catalog.GetString("Invert R & B");
			this.cbxBGR.DrawIndicator = true;
			this.cbxBGR.UseUnderline = true;
			this.hbox3.Add(this.cbxBGR);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.cbxBGR]));
			w10.Position = 8;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnLoadImg = new global::Gtk.Button();
			this.btnLoadImg.CanFocus = true;
			this.btnLoadImg.Name = "btnLoadImg";
			this.btnLoadImg.UseUnderline = true;
			this.btnLoadImg.Label = global::Mono.Unix.Catalog.GetString("Load image");
			this.hbox3.Add(this.btnLoadImg);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnLoadImg]));
			w11.Position = 9;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnSaveIMG = new global::Gtk.Button();
			this.btnSaveIMG.Sensitive = false;
			this.btnSaveIMG.CanFocus = true;
			this.btnSaveIMG.Name = "btnSaveIMG";
			this.btnSaveIMG.UseUnderline = true;
			this.btnSaveIMG.Label = global::Mono.Unix.Catalog.GetString("Save to file");
			this.hbox3.Add(this.btnSaveIMG);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnSaveIMG]));
			w12.Position = 10;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.imgRAW = new global::Gtk.Image();
			this.imgRAW.Name = "imgRAW";
			this.eventbox1.Add(this.imgRAW);
			this.vbox3.Add(this.eventbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.eventbox1]));
			w15.Position = 1;
			this.notebook1.Add(this.vbox3);
			global::Gtk.Notebook.NotebookChild w16 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox3]));
			w16.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Image");
			this.notebook1.SetTabLabel(this.vbox3, this.label2);
			this.label2.ShowAll();
			this.Add(this.notebook1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btnLoadImg.Clicked += new global::System.EventHandler(this.OnBtnLoadImgClicked);
			this.btnSaveIMG.Clicked += new global::System.EventHandler(this.OnBtnSaveIMGClicked);
			this.eventbox1.ScrollEvent += new global::Gtk.ScrollEventHandler(this.OnImgRAWScrollEvent);
			this.imgRAW.ScrollEvent += new global::Gtk.ScrollEventHandler(this.OnImgRAWScrollEvent);
		}
	}
}
