
// This file has been generated by the GUI designer. Do not modify.
namespace TRLevelUtility
{
	public partial class TwoBaseEntry
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.SpinButton tbeSb1;

		private global::Gtk.SpinButton tbeSb2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TRLevelUtility.TwoBaseEntry
			global::Stetic.BinContainer.Attach(this);
			this.Name = "TRLevelUtility.TwoBaseEntry";
			// Container child TRLevelUtility.TwoBaseEntry.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tbeSb1 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.tbeSb1.CanFocus = true;
			this.tbeSb1.Name = "tbeSb1";
			this.tbeSb1.Adjustment.PageIncrement = 10D;
			this.tbeSb1.ClimbRate = 1D;
			this.tbeSb1.Numeric = true;
			this.hbox1.Add(this.tbeSb1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.tbeSb1]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tbeSb2 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.tbeSb2.CanFocus = true;
			this.tbeSb2.Name = "tbeSb2";
			this.tbeSb2.Adjustment.PageIncrement = 10D;
			this.tbeSb2.ClimbRate = 1D;
			this.tbeSb2.Numeric = true;
			this.hbox1.Add(this.tbeSb2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.tbeSb2]));
			w2.Position = 1;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.tbeSb1.ValueChanged += new global::System.EventHandler(this.OntbeSb1Changed);
			this.tbeSb2.Input += new global::Gtk.InputHandler(this.OntbeSb2Input);
			this.tbeSb2.Output += new global::Gtk.OutputHandler(this.OntbeSb2Output);
			this.tbeSb2.ValueChanged += new global::System.EventHandler(this.OntbeSb2Changed);
		}
	}
}
