
// This file has been generated by the GUI designer. Do not modify.
namespace TRLevelUtility
{
	public partial class PgCDAudio
	{
		private global::Gtk.VBox vbox2;

		private global::TRLevelUtility.ListAddRem larMain;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label lblCur;

		private global::Gtk.HScale scMedia;

		private global::Gtk.Label lblDur;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnPlay;

		private global::Gtk.Button btnStop;

		private global::Gtk.Button btnSaveSel;

		private global::Gtk.Button btnSaveAll;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TRLevelUtility.PgCDAudio
			global::Stetic.BinContainer.Attach(this);
			this.Name = "TRLevelUtility.PgCDAudio";
			// Container child TRLevelUtility.PgCDAudio.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.larMain = new global::TRLevelUtility.ListAddRem();
			this.larMain.Events = ((global::Gdk.EventMask)(256));
			this.larMain.Name = "larMain";
			this.larMain.HideAddRem = true;
			this.larMain.SelectedRow = 0;
			this.larMain.MaxCount = 0;
			this.vbox2.Add(this.larMain);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.larMain]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblCur = new global::Gtk.Label();
			this.lblCur.Name = "lblCur";
			this.lblCur.LabelProp = global::Mono.Unix.Catalog.GetString("0:00");
			this.hbox3.Add(this.lblCur);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblCur]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(6));
			// Container child hbox3.Gtk.Box+BoxChild
			this.scMedia = new global::Gtk.HScale(null);
			this.scMedia.Sensitive = false;
			this.scMedia.CanFocus = true;
			this.scMedia.Name = "scMedia";
			this.scMedia.Adjustment.Upper = 100D;
			this.scMedia.Adjustment.PageIncrement = 10D;
			this.scMedia.Adjustment.StepIncrement = 1D;
			this.scMedia.DrawValue = false;
			this.scMedia.Digits = 0;
			this.scMedia.ValuePos = ((global::Gtk.PositionType)(0));
			this.hbox3.Add(this.scMedia);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.scMedia]));
			w3.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblDur = new global::Gtk.Label();
			this.lblDur.Name = "lblDur";
			this.lblDur.LabelProp = global::Mono.Unix.Catalog.GetString("0:00");
			this.hbox3.Add(this.lblDur);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblDur]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(6));
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnPlay = new global::Gtk.Button();
			this.btnPlay.Sensitive = false;
			this.btnPlay.CanFocus = true;
			this.btnPlay.Name = "btnPlay";
			this.btnPlay.UseUnderline = true;
			this.btnPlay.Label = global::Mono.Unix.Catalog.GetString("Play");
			global::Gtk.Image w6 = new global::Gtk.Image();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-play", global::Gtk.IconSize.LargeToolbar);
			this.btnPlay.Image = w6;
			this.hbox1.Add(this.btnPlay);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnPlay]));
			w7.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnStop = new global::Gtk.Button();
			this.btnStop.Sensitive = false;
			this.btnStop.CanFocus = true;
			this.btnStop.Name = "btnStop";
			this.btnStop.UseUnderline = true;
			this.btnStop.Label = global::Mono.Unix.Catalog.GetString("Stop");
			global::Gtk.Image w8 = new global::Gtk.Image();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-stop", global::Gtk.IconSize.LargeToolbar);
			this.btnStop.Image = w8;
			this.hbox1.Add(this.btnStop);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnStop]));
			w9.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSaveSel = new global::Gtk.Button();
			this.btnSaveSel.Sensitive = false;
			this.btnSaveSel.CanFocus = true;
			this.btnSaveSel.Name = "btnSaveSel";
			this.btnSaveSel.UseUnderline = true;
			this.btnSaveSel.Label = global::Mono.Unix.Catalog.GetString("Save selected");
			global::Gtk.Image w10 = new global::Gtk.Image();
			w10.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.LargeToolbar);
			this.btnSaveSel.Image = w10;
			this.hbox1.Add(this.btnSaveSel);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSaveSel]));
			w11.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSaveAll = new global::Gtk.Button();
			this.btnSaveAll.CanFocus = true;
			this.btnSaveAll.Name = "btnSaveAll";
			this.btnSaveAll.UseUnderline = true;
			this.btnSaveAll.Label = global::Mono.Unix.Catalog.GetString("Save all");
			global::Gtk.Image w12 = new global::Gtk.Image();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.LargeToolbar);
			this.btnSaveAll.Image = w12;
			this.hbox1.Add(this.btnSaveAll);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSaveAll]));
			w13.Position = 3;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btnPlay.Clicked += new global::System.EventHandler(this.OnBtnPlayClicked);
			this.btnStop.Clicked += new global::System.EventHandler(this.OnBtnStopClicked);
			this.btnSaveSel.Clicked += new global::System.EventHandler(this.OnBtnSaveSelClicked);
		}
	}
}
