
// This file has been generated by the GUI designer. Do not modify.
namespace TRLevelUtility
{
	public partial class TPCImportDlg
	{
		private global::Gtk.Table table1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.VBox vbox2;

		private global::Gtk.RadioButton rbTR2;

		private global::Gtk.RadioButton rbTR2b;

		private global::Gtk.RadioButton rbTR3;

		private global::Gtk.VBox vbox3;

		private global::Gtk.RadioButton rbPC;

		private global::Gtk.RadioButton rbPSX;

		private global::Gtk.Button button10;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TRLevelUtility.TPCImportDlg
			this.Name = "TRLevelUtility.TPCImportDlg";
			this.Title = global::Mono.Unix.Catalog.GetString("Open DAT file");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child TRLevelUtility.TPCImportDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(18));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Game version");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Platform");
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Homogeneous = true;
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.rbTR2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Tomb Raider 2"));
			this.rbTR2.CanFocus = true;
			this.rbTR2.Name = "rbTR2";
			this.rbTR2.Active = true;
			this.rbTR2.DrawIndicator = true;
			this.rbTR2.UseUnderline = true;
			this.rbTR2.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox2.Add(this.rbTR2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.rbTR2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.rbTR2b = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Tomb Raider 2 Beta"));
			this.rbTR2b.CanFocus = true;
			this.rbTR2b.Name = "rbTR2b";
			this.rbTR2b.DrawIndicator = true;
			this.rbTR2b.UseUnderline = true;
			this.rbTR2b.Group = this.rbTR2.Group;
			this.vbox2.Add(this.rbTR2b);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.rbTR2b]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.rbTR3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Tomb Raider 3"));
			this.rbTR3.CanFocus = true;
			this.rbTR3.Name = "rbTR3";
			this.rbTR3.DrawIndicator = true;
			this.rbTR3.UseUnderline = true;
			this.rbTR3.Group = this.rbTR2.Group;
			this.vbox2.Add(this.rbTR3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.rbTR3]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.table1.Add(this.vbox2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox2]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.rbPC = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("PC"));
			this.rbPC.CanFocus = true;
			this.rbPC.Name = "rbPC";
			this.rbPC.Active = true;
			this.rbPC.DrawIndicator = true;
			this.rbPC.UseUnderline = true;
			this.rbPC.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox3.Add(this.rbPC);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.rbPC]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.rbPSX = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("PSX"));
			this.rbPSX.CanFocus = true;
			this.rbPSX.Name = "rbPSX";
			this.rbPSX.DrawIndicator = true;
			this.rbPSX.UseUnderline = true;
			this.rbPSX.Group = this.rbPC.Group;
			this.vbox3.Add(this.rbPSX);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.rbPSX]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.table1.Add(this.vbox3);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox3]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.table1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1[this.table1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Internal child TRLevelUtility.TPCImportDlg.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button10 = new global::Gtk.Button();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseStock = true;
			this.button10.UseUnderline = true;
			this.button10.Label = "gtk-ok";
			this.AddActionWidget(this.button10, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12[this.button10]));
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 255;
			this.DefaultHeight = 205;
			this.Show();
			this.rbPC.Toggled += new global::System.EventHandler(this.OnRbPCToggled);
			this.rbTR2b.Toggled += new global::System.EventHandler(this.OnRbTR2bToggled);
		}
	}
}
