
// This file has been generated by the GUI designer. Do not modify.
namespace TRLevelUtility
{
	public partial class TR4ImportDlg
	{
		private global::Gtk.Table table1;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.RadioButton rbTR4;

		private global::Gtk.RadioButton rbTR5;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TRLevelUtility.TR4ImportDlg
			this.Name = "TRLevelUtility.TR4ImportDlg";
			this.Title = global::Mono.Unix.Catalog.GetString("Open DAT file");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child TRLevelUtility.TR4ImportDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(18));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Game version");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Homogeneous = true;
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.rbTR4 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Tomb Raider 4"));
			this.rbTR4.CanFocus = true;
			this.rbTR4.Name = "rbTR4";
			this.rbTR4.DrawIndicator = true;
			this.rbTR4.UseUnderline = true;
			this.rbTR4.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox2.Add(this.rbTR4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.rbTR4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.rbTR5 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Tomb Raider 5"));
			this.rbTR5.CanFocus = true;
			this.rbTR5.Name = "rbTR5";
			this.rbTR5.DrawIndicator = true;
			this.rbTR5.UseUnderline = true;
			this.rbTR5.Group = this.rbTR4.Group;
			this.vbox2.Add(this.rbTR5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.rbTR5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.table1.Add(this.vbox2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox2]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.table1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1[this.table1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Internal child TRLevelUtility.TR4ImportDlg.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7[this.buttonOk]));
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 136;
			this.DefaultHeight = 170;
			this.Show();
		}
	}
}
