namespace NLibsndfile.Native
{
    public enum LibsndfileError
    {
        NoError = 0,
        UnrecognisedFormat = 1,
        System = 2,
        MalformedFile = 3,
        UnsupportedEncoding = 4,

        ZeroMajorFormat,
        ZeroMinorFormat,
        BadFile,
        BadFileRead,
        OpenFailed,
        BadSndfilePtr,
        BadSfInfoPtr,
        BadSfIncomplete,
        BadFilePtr,
        BadIntPtr,
        BadStatSize,
        NoTempDir,
        MallocFailed,
        Unimplemented,
        BadReadAlign,
        BadWriteAlign,
        UnknownFormat,
        NotReadmode,
        NotWritemode,
        BadModeRw,
        BadSfInfo,
        BadOffset,
        NoEmbedSupport,
        NoEmbeddedRdwr,
        NoPipeWrite,

        Internal,
        BadCommandParam,
        BadEndian,
        ChannelCountZero,
        ChannelCount,
        ChannelCountBad,

        BadVirtualIo,

        InterleaveMode,
        InterleaveSeek,
        InterleaveRead,

        BadSeek,
        NotSeekable,
        AmbiguousSeek,
        WrongSeek,
        SeekFailed,

        BadOpenMode,
        OpenPipeRdwr,
        RdwrPosition,
        RdwrBadHeader,
        CmdHasData,
        BadBroadcastInfoSize,
        BadBroadcastInfoTooBig,
        BadCartInfoSize,
        BadCartInfoTooBig,

        StrNoSupport,
        StrNotWrite,
        StrMaxData,
        StrMaxCount,
        StrBadType,
        StrNoAddEnd,
        StrBadString,
        StrWeird,

        WavNoRiff,
        WavNoWave,
        WavNoFmt,
        WavBadFmt,
        WavFmtShort,
        WavBadFact,
        WavBadPeak,
        WavPeakB4Fmt,
        WavBadFormat,
        WavBadBlockalign,
        WavNoData,
        WavBadList,
        WavAdpcmNot4Bit,
        WavAdpcmChannels,
        WavAdpcmSamples,
        WavGsm610Format,
        WavUnknownChunk,
        WavWvpkData,

        AiffNoForm,
        AiffAiffNoForm,
        AiffCommNoForm,
        AiffSsndNoComm,
        AiffUnknownChunk,
        AiffCommChunkSize,
        AiffBadCommChunk,
        AiffPeakB4Comm,
        AiffBadPeak,
        AiffNoSsnd,
        AiffNoData,
        AiffRwSsndNotLast,

        AuUnknownFormat,
        AuNoDotsnd,
        AuEmbedBadLen,

        RawReadBadSpec,
        RawBadBitwidth,
        RawBadFormat,

        PafNoMarker,
        PafVersion,
        PafUnknownFormat,
        PafShortHeader,
        PafBadChannels,

        SvxNoForm,
        SvxNoBody,
        SvxNoData,
        SvxBadComp,
        SvxBadNameLength,

        NistBadHeader,
        NistCrlfConverison,
        NistBadEncoding,

        VocNoCreative,
        VocBadFormat,
        VocBadVersion,
        VocBadMarker,
        VocBadSections,
        VocMultiSamplerate,
        VocMultiSection,
        VocMultiParam,
        VocSectionCount,
        VocNoPipe,

        IrcamNoMarker,
        IrcamBadChannels,
        IrcamUnknownFormat,

        W6464Bit,
        W64NoRiff,
        W64NoWave,
        W64NoData,
        W64AdpcmNot4Bit,
        W64AdpcmChannels,
        W64Gsm610Format,

        Mat4BadName,
        Mat4NoSamplerate,

        Mat5BadEndian,
        Mat5NoBlock,
        Mat5SampleRate,

        PvfNoPvf1,
        PvfBadHeader,
        PvfBadBitwidth,

        DwvwBadBitwidth,
        G72XNotMono,

        XiBadHeader,
        XiExcessSamples,
        XiNoPipe,

        HtkNoPipe,

        SdsNotSds,
        SdsBadBitWidth,

        Sd2FdDisallowed,
        Sd2BadDataOffset,
        Sd2BadMapOffset,
        Sd2BadDataLength,
        Sd2BadMapLength,
        Sd2BadRsrc,
        Sd2BadSampleSize,

        FlacBadHeader,
        FlacNewDecoder,
        FlacInitDecoder,
        FlacLostSync,
        FlacBadSampleRate,
        FlacUnkownError,

        WveNotWve,
        WveNoPipe,

        VorbisEncoderBug,

        Rf64NotRf64,
        Rf64PeakB4Fmt,
        Rf64NoData,

        BadChunkPtr,
        UnknownChunk,
        BadChunkFormat,
        BadChunkMarker,
        BadChunkDataPtr,
        AlacFailTmpfile,
        FilenameTooLong,
        MaxError /* This must be last in list. */
    }
}